Repository woowacourse-teams/2023-haru-study, pull requests merged in 2023-10, with the labels that each got.

#604 [FE] record 관련 api 수정 및 적용
  frontend/__test__/StudyRecord.test.tsx
  frontend/src/api/index.ts
  frontend/src/components/record/ParticipantRecord/ParticipantRecord.tsx
  frontend/src/components/record/ParticipantRecordList/ParticipantRecordList.tsx
  frontend/src/components/record/ProgressRecordList/ProgressRecordList.tsx
  frontend/src/components/record/ResetButton/ResetButton.tsx
  frontend/src/components/record/StudyRecordContents/StudyRecordContents.tsx
  frontend/src/components/record/hooks/useMemberRecordContents.ts
  frontend/src/components/record/hooks/useParticipantRecordContents.ts
  frontend/src/components/record/hooks/useStudyMembers.ts
  frontend/src/components/record/hooks/useStudyParticipants.ts
  frontend/src/mocks/handlers/studyRecordHandlers.ts
  frontend/src/types/api.ts
  frontend/src/types/study.ts
Labels: FE, refactor

#609 [FE] 개설하기, 참여하기, 준비하기 api 변경사항 적용
  frontend/__test__/StudyPreparationPage.test.tsx
  frontend/src/api/index.ts
  frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
  frontend/src/components/create/hooks/useCreateStudy.ts
  frontend/src/components/mode/StudyModeContent/StudyModeContent.tsx
  frontend/src/components/participation/ParticipationCodeInput/ParticipationCodeInput.tsx
  frontend/src/components/participation/PrticipationContents/MemberRegister/MemberRegister.tsx
  frontend/src/components/participation/PrticipationContents/MemberRestart/MemberRestart.tsx
  frontend/src/components/participation/PrticipationContents/PartcipationContents.tsx
  frontend/src/components/participation/hooks/useCheckParticipants.ts
  frontend/src/components/participation/hooks/useCheckParticipationCode.ts
  frontend/src/components/participation/hooks/useCheckProgresses.ts
  frontend/src/components/participation/hooks/useRegisterParticipants.ts
  frontend/src/components/participation/hooks/useRegisterProgress.ts
  frontend/src/mocks/handlers/createStudyHandlers.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/participantsHandlers.ts
  frontend/src/mocks/handlers/studyInfoHandlers.ts
  frontend/src/pages/CreateStudy.tsx
  frontend/src/pages/StudyPreparation.tsx
  frontend/src/types/api.ts
  frontend/src/types/study.ts
Labels: FE, refactor

#608 [BE] 로그아웃 기능 및 인증 관련 정비
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
  backend/src/main/java/harustudy/backend/auth/repository/RefreshTokenRepository.java
  backend/src/main/java/harustudy/backend/auth/service/AuthService.java
  backend/src/test/java/harustudy/backend/auth/service/AuthServiceTest.java
  backend/src/test/java/harustudy/backend/integration/AuthIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
Labels: BE, feature

#615 [BE] CompositeOauthClient를 일급 컬렉션으로 변경
  backend/src/main/java/harustudy/backend/auth/domain/oauth/CompositeOauthClient.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/GoogleOauthClient.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/KakaoOauthClient.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClient.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClients.java
  backend/src/main/java/harustudy/backend/auth/service/OauthLoginFacade.java
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/auth/service/AuthServiceTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
Labels: BE, refactor

#605 [BE] 카카오 OAuth 인증 추가
  backend/src/main/java/harustudy/backend/auth/config/OauthProperties.java
  backend/src/main/java/harustudy/backend/auth/config/OauthProperty.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/GoogleOauthClient.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/KakaoOauthClient.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClient.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClients.java
  backend/src/main/java/harustudy/backend/auth/exception/OauthServerException.java
  backend/src/main/java/harustudy/backend/auth/infrastructure/GoogleOauthClient.java
  backend/src/main/java/harustudy/backend/auth/service/OauthLoginFacade.java
  backend/src/main/java/harustudy/backend/auth/util/OauthUserInfoExtractor.java
  backend/src/main/java/harustudy/backend/auth/util/OauthWebClient.java
  backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/common/exception/HaruStudyException.java
  backend/src/main/java/harustudy/backend/member/domain/LoginType.java
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/auth/service/AuthServiceTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
  backend/src/test/resources/application.yml
Labels: BE, feature

#611 [BE] 날짜 기반 스터디 기록 조회를 위한 view 전용 API 구현
  backend/src/main/java/harustudy/backend/study/repository/StudyRepository.java
  backend/src/main/java/harustudy/backend/view/controller/ViewController.java
  backend/src/main/java/harustudy/backend/view/dto/CalendarStudyRecordsResponse.java
  backend/src/main/java/harustudy/backend/view/dto/PageInfoResponse.java
  backend/src/main/java/harustudy/backend/view/dto/StudyRecordResponse.java
  backend/src/main/java/harustudy/backend/view/dto/StudyRecordsPageResponse.java
  backend/src/main/java/harustudy/backend/view/service/ViewService.java
  backend/src/main/java/harustudy/backend/view/utils/LocalDateConverter.java
  backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java
  backend/src/test/java/harustudy/backend/integration/PollingIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ViewIntegrationTest.java
  backend/src/test/java/harustudy/backend/member/service/MemberServiceTest.java
  backend/src/test/java/harustudy/backend/view/service/ViewServiceTest.java
  backend/src/test/java/harustudy/backend/view/utils/LocalDateConverterTest.java
Labels: BE, feature

#618 [FE] MSW 코드 리팩토링
  frontend/src/mocks/handlers/authHandler.ts
  frontend/src/mocks/handlers/contentsHandler.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/participantsHandler.ts
  frontend/src/mocks/handlers/participantsHandlers.ts
  frontend/src/mocks/handlers/pollingHandler.ts
  frontend/src/mocks/handlers/studiesHandler.ts
  frontend/src/mocks/handlers/studyBoardHandler.ts
  frontend/src/mocks/handlers/studyInfoHandlers.ts
  frontend/src/mocks/mockData.ts
Labels: FE, refactor

#613 [FE] member record Calendar 기능 추가
  frontend/__test__/MemberRecord.test.tsx
  frontend/src/api/index.ts
  frontend/src/components/landing/MemberProfile/MemberProfile.tsx
  frontend/src/components/record/CalendarDay/CalendarDay.tsx
  frontend/src/components/record/CalendarDayOfWeeks/CalendarDayOfWeeks.tsx
  frontend/src/components/record/MemberRecordCalendar/MemberRecordCalendar.tsx
  frontend/src/components/record/MemberRecordCalendarControlBar/MemberRecordCalendarControlBar.tsx
  frontend/src/components/record/MemberRecordCalendarDay/MemberRecordCalendarDay.tsx
  frontend/src/components/record/MemberRecordCalendarDay/MemberRecordCalendarDaySkeleton.tsx
  frontend/src/components/record/MemberRecordCalendarDays/MemberRecordCalendarDays.tsx
  frontend/src/components/record/MemberRecordContents/MemberRecordContents.tsx
  frontend/src/components/record/MemberRecordItem/MemberRecordItem.tsx
  frontend/src/components/record/MemberRecordItems/MemberRecordItems.tsx
  frontend/src/components/record/MemberRecordItems/MemberRecordItemsSkeleton.tsx
  frontend/src/components/record/MemberRecordList/MemberRecordList.tsx
  frontend/src/components/record/MemberRecords/MemberRecords.tsx
  frontend/src/components/record/MemberRecordsModal/MemberRecordsModal.tsx
  frontend/src/components/record/PaginationButton/PaginationButton.tsx
  frontend/src/components/record/PeriodSelectCalendar/PeriodSelectCalendar.tsx
  frontend/src/components/record/PeriodSelectionBar/PeriodSelectionBar.tsx
  frontend/src/components/record/contexts/MemberRecordPeriodProvider.tsx
  frontend/src/components/record/hooks/useMemberCalendarRecord.ts
  frontend/src/components/record/hooks/useMemberCalendarRecordSearchParams.ts
  frontend/src/components/record/hooks/useMemberListRecord.ts
  frontend/src/components/record/hooks/useMemberStudyListData.ts
  frontend/src/constants/record.ts
  frontend/src/hooks/common/useCalendar.ts
  frontend/src/hooks/common/useOutsideClick.ts
  frontend/src/hooks/common/useSearchParams.ts
  frontend/src/mocks/handlers/studyRecordHandlers.ts
  frontend/src/pages/layout/RecordLayout.tsx
  frontend/src/router/index.tsx
  frontend/src/types/api.ts
  frontend/src/types/record.ts
  frontend/src/utils/calendar.ts
  frontend/src/utils/format.ts
Labels: FE, feature, UI

#623 [BE] 기존 서비스 로직에서 발생하는 N+1 문제 개선
  backend/src/main/java/harustudy/backend/study/repository/StudyRepository.java
  backend/src/main/java/harustudy/backend/study/service/StudyService.java
Labels: BE, refactor

#621 [FE] 로그아웃 처리 로직 변경
  frontend/src/api/index.ts
  frontend/src/contexts/MemberInfoProvider.tsx
  frontend/src/mocks/handlers/authHandler.ts
Labels: FE, feature

#629 [FE] 목록 조회 totalPages 오류 수정 및 EmptyMemberRecord 개선
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/components/record/hooks/useMemberListRecord.ts
  frontend/src/components/record/member/period/EmptyMemberRecord/EmptyMemberRecord.tsx
  frontend/src/components/record/member/period/MemberRecordPeriod/MemberRecordPeriod.tsx
  frontend/src/mocks/handlers/queryHandler.ts
  frontend/src/mocks/mockData.ts
Labels: FE, refactor, UI

#627 [BE] view API 테스트에 잘못 추가된 출력문 삭제
  backend/src/test/java/harustudy/backend/view/service/ViewServiceTest.java
Labels: BE, feature

#639 [ALL] 서버 분리로 인한 젠킨스 스크립트의 서버 설정 변경
  jenkins/backend-develop.jenkinsfile
  jenkins/frontend-develop.jenkinsfile
Labels: devops

#637 [BE] README 업데이트
  README.md
  backend/.gitignore
Labels: documentation

#642 [BE] KAKAO UserInfo 파싱 변경
  backend/src/main/java/harustudy/backend/auth/dto/UserInfo.java
  backend/src/main/java/harustudy/backend/auth/exception/UserInfoFormatException.java
  backend/src/main/java/harustudy/backend/auth/util/OauthUserInfoExtractor.java
  backend/src/test/java/harustudy/backend/auth/dto/UserInfoTest.java
Labels: bug, BE, refactor

#644 [BE] 로그아웃 시의 쿠키의 path 수정
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
Labels: bug, BE, feature

#649 [BE] 소셜 로그인 로직 개선
  backend/src/main/java/harustudy/backend/auth/domain/oauth/GoogleOauthClient.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/KakaoOauthClient.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClient.java
  backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClients.java
Labels: BE, refactor

#647 [FE] 스터디 실시간 동기화 기능
  frontend/src/App.tsx
  frontend/src/api/index.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/CircularProgress/CircularProgress.tsx
  frontend/src/components/common/ErrorFallback/ErrorFallback.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx
  frontend/src/components/common/RefreshButton/RefreshButton.tsx
  frontend/src/components/common/ScrollToTop/ScrollToTop.tsx
  frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
  frontend/src/components/create/hooks/useCreateStudy.ts
  frontend/src/components/lobby/ParticipantCodeCopier/ParticipantCodeCopier.tsx
  frontend/src/components/lobby/ParticipantList/ParticipantList.tsx
  frontend/src/components/lobby/StudyLobbyContents/StudyLobbyContents.tsx
  frontend/src/components/lobby/hooks/useLobbyInfoPolling.ts
  frontend/src/components/lobby/hooks/useStudyLobby.ts
  frontend/src/components/participation/ParticipationCodeInput/ParticipationCodeInput.tsx
  frontend/src/components/participation/PrticipationContents/MemberRegister/MemberRegister.tsx
  frontend/src/components/participation/PrticipationContents/MemberRestart/MemberRestart.tsx
  frontend/src/components/participation/PrticipationContents/ParticipationCodeCopier/ParticipationCodeCopier.tsx
  frontend/src/components/participation/hooks/useCheckParticipationCode.ts
  frontend/src/components/progress/GuideModal/GuideModal.tsx
  frontend/src/components/progress/PlanningForm/PlanningForm.tsx
  frontend/src/components/progress/ProgressPolling/ProgressPolling.tsx
  frontend/src/components/progress/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/progress/Sidebar/Sidebar.tsx
  frontend/src/components/progress/StudyBoard/StudyBoard.tsx
  frontend/src/components/progress/StudyInfoModal/StudyInfoModal.tsx
  frontend/src/components/progress/StudyingForm/StudyingForm.tsx
  frontend/src/components/progress/Timer/Timer.stories.tsx
  frontend/src/components/progress/Timer/Timer.tsx
  frontend/src/components/progress/hooks/useParticipantsSubmit.ts
  frontend/src/components/progress/hooks/usePlanningForm.ts
  frontend/src/components/progress/hooks/useRetrospectForm.ts
  frontend/src/components/progress/hooks/useStepTimer.ts
  frontend/src/components/progress/hooks/useStudyingForm.ts
  frontend/src/components/record/hooks/useStudyData.ts
  frontend/src/components/waiting/StudyWaitingMembers/StudyWaitingMembers.tsx
  frontend/src/components/waiting/StudyWaitingMembers/StudyWaitingMemebers.stories.tsx
  frontend/src/constants/routes.ts
  frontend/src/constants/study.ts
  frontend/src/contexts/StudyProgressProvider.tsx
  frontend/src/hooks/api/useFetch.ts
  frontend/src/hooks/api/useMutation.ts
  frontend/src/hooks/common/useClipBoard.ts
  frontend/src/mocks/handlers/pollingHandler.ts
  frontend/src/mocks/handlers/studiesHandler.ts
  frontend/src/mocks/mockData.ts
  frontend/src/pages/StudyLobby.tsx
  frontend/src/pages/layout/StudyParticipationLayout.tsx
  frontend/src/router/index.tsx
  frontend/src/types/api.ts
  frontend/src/types/study.ts
Labels: FE, feature, UI

#663 [BE] 대기방에서 방장이 나갔을 때 기존 참여자들에게 빈 배열 응답
  backend/src/main/java/harustudy/backend/polling/service/PollingService.java
  backend/src/test/java/harustudy/backend/polling/service/PollingServiceTest.java
Labels: BE, feature

#664 [BE] 목표 작성 없이 방장이 강제로 다음 단계로 넘어가면 studyStep이 적절하지 않다고 표시되는 문제 수정
  backend/src/main/java/harustudy/backend/content/service/ContentService.java
  backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java
Labels: BE, feature

#667 [FE] 스터디 동기화 기능 버그 수정 및 추가 기능 구현
  frontend/src/api/index.ts
  frontend/src/components/lobby/ParticipantList/ParticipantList.tsx
  frontend/src/components/lobby/hooks/useStudyLobby.ts
  frontend/src/components/participation/PrticipationContents/MemberRestart/MemberRestart.tsx
  frontend/src/components/progress/ProgressPolling/ProgressPolling.tsx
  frontend/src/components/progress/Sidebar/Sidebar.tsx
  frontend/src/components/progress/StudyBoard/StudyBoard.tsx
  frontend/src/components/progress/StudyInfoModal/StudyInfoModal.tsx
  frontend/src/types/api.ts
Labels: bug, FE, feature

#669 [FE] 달력 모달 스크롤 문제 해결
  frontend/src/components/record/member/calendar/MemberRecordListModal/MemberRecordListModal.tsx
Labels: bug, FE, UI

#676 [BE] 무중단 배포를 위한 테이블 네이밍 임시 변경
  backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
Labels: BE, feature

#655 [BE] 스터디 동시 진행 기능 업데이트를 위한 무중단 배포 준비
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
  backend/src/main/java/harustudy/backend/common/exception/ErrorCodeView.java
  backend/src/main/java/harustudy/backend/config/FilterConfig.java
  backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
  backend/src/main/java/harustudy/backend/content/controller/ContentController.java
  backend/src/main/java/harustudy/backend/member/controller/MemberController.java
  backend/src/main/java/harustudy/backend/participant/controller/ParticipantController.java
  backend/src/main/java/harustudy/backend/participantcode/controller/ParticipantCodeController.java
  backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
  backend/src/main/java/harustudy/backend/polling/controller/PollingController.java
  backend/src/main/java/harustudy/backend/study/controller/StudyController.java
  backend/src/main/java/harustudy/backend/view/controller/ViewController.java
  backend/src/main/resources/templates/error-code.html
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/integration/AuthIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ContentIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/MemberIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ParticipantIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/PollingIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ViewIntegrationTest.java
Labels: BE, feature

#671 [BE] 이메일 기반으로 Oauth User를 찾는 로직 변경
  backend/src/main/java/harustudy/backend/auth/service/AuthService.java
  backend/src/main/java/harustudy/backend/member/repository/MemberRepository.java
  backend/src/test/java/harustudy/backend/auth/service/AuthServiceTest.java
Labels: BE, refactor

#678 [FE] 프론트 무중단 배포 준비
  frontend/__test__/StudyPreparationPage.test.tsx
  frontend/__test__/StudyRecord.test.tsx
  frontend/src/api/httpInstance.ts
  frontend/src/api/index.ts
  frontend/src/mocks/handlers/authHandler.ts
  frontend/src/mocks/handlers/contentsHandler.ts
  frontend/src/mocks/handlers/participantsHandler.ts
  frontend/src/mocks/handlers/pollingHandler.ts
  frontend/src/mocks/handlers/queryHandler.ts
  frontend/src/mocks/handlers/studiesHandler.ts
Labels: FE, refactor

#679 [FE] 아이폰 사파리 접속시 화면 짤리는 문제 해결
  frontend/src/components/progress/StudyBoard/StudyBoard.tsx
  frontend/src/styles/common.ts
Labels: bug, FE, UI

#683 [ALL] 레포지토리 README 작성 완료
  README.md
Labels: documentation

#688 [FE] 어드민 젠킨스 스크립트 변경
  jenkins/frontend-admin-develop.jenkinsfile
  jenkins/frontend-admin-production.jenkinsfile
Labels: devops, admin

#692 [FE] admin 경로 문제 수정
  admin/src/constants/routes.ts
Labels: admin

#686 [FE] 멤버, 스터디 기록 Cache 적용
  frontend/src/components/common/CircularProgress/CircularProgress.tsx
  frontend/src/components/landing/MemberProfile/MemberProfile.tsx
  frontend/src/components/landing/hooks/usePreFetchMemberRecord.ts
  frontend/src/components/record/hooks/useMemberCalendarRecord.ts
  frontend/src/components/record/hooks/useMemberListRecord.ts
  frontend/src/components/record/hooks/useParticipantRecordContents.ts
  frontend/src/components/record/hooks/useStudyData.ts
  frontend/src/components/record/hooks/useStudyParticipants.ts
  frontend/src/components/record/member/calendar/MemberRecordCalendarDayItem/MemberRecordCalendarDayItemSkeleton.tsx
  frontend/src/components/record/member/calendar/MemberRecordCalendarDayList/MemberRecordCalendarDayList.tsx
  frontend/src/components/record/member/calendar/MemberRecordListModal/MemberRecordListModal.tsx
  frontend/src/components/record/member/period/MemberRecordPeriod/MemberRecordPeriod.tsx
  frontend/src/components/record/member/period/PaginationButton/PaginationButton.tsx
  frontend/src/components/record/study/ParticipantRecordItem/ParticipantRecordItem.tsx
  frontend/src/components/record/study/ParticipantRecordList/ParticipantRecordList.tsx
  frontend/src/components/record/study/ResetButton/ResetButton.tsx
  frontend/src/components/record/study/StudyRecordContents/StudyRecordContents.tsx
  frontend/src/hooks/api/useCacheFetch.ts
  frontend/src/hooks/api/usePreFetch.ts
  frontend/src/mocks/handlers/queryHandler.ts
  frontend/src/utils/CacheStorage.ts
  frontend/src/utils/calendar.ts
  frontend/src/utils/debouncing.ts
Labels: FE, feature, refactor, chore, UI

#694 [FE] 비회원 프로필이 보이지 않는 문제
  frontend/src/components/landing/MemberProfile/MemberProfile.tsx
  frontend/src/components/landing/hooks/usePreFetchMemberCalendarRecord.ts
  frontend/src/components/record/hooks/useMemberCalendarRecord.ts
  frontend/src/components/record/hooks/useMemberListRecord.ts
  frontend/src/components/record/hooks/useParticipantRecordContents.ts
  frontend/src/components/record/hooks/useStudyData.ts
  frontend/src/components/record/hooks/useStudyParticipants.ts
Labels: bug, FE

#674 [BE] 어드민 페이지 구현
  backend/src/main/java/harustudy/backend/admin/AdminInterceptor.java
  backend/src/main/java/harustudy/backend/admin/controller/AdminController.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminContentResponse.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminContentsResponse.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminLoginRequest.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminMemberResponse.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminMembersResponse.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminParticipantCodeResponse.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminParticipantResponse.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminParticipantsResponse.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminStudiesResponse.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminStudyContentResponse.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminStudyResponse.java
  backend/src/main/java/harustudy/backend/admin/entity/Admin.java
  backend/src/main/java/harustudy/backend/admin/entity/AdminSession.java
  backend/src/main/java/harustudy/backend/admin/exception/AdminNotFoundException.java
  backend/src/main/java/harustudy/backend/admin/exception/AdminSessionExpiredException.java
  backend/src/main/java/harustudy/backend/admin/exception/SessionNotFoundException.java
  backend/src/main/java/harustudy/backend/admin/repository/AdminRepository.java
  backend/src/main/java/harustudy/backend/admin/repository/AdminSessionRepository.java
  backend/src/main/java/harustudy/backend/admin/service/AdminAuthService.java
  backend/src/main/java/harustudy/backend/admin/service/AdminService.java
  backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
  backend/src/main/java/harustudy/backend/content/repository/ContentRepository.java
  backend/src/main/java/harustudy/backend/member/repository/MemberRepository.java
  backend/src/main/java/harustudy/backend/study/repository/StudyRepository.java
  backend/src/test/java/harustudy/backend/admin/entity/AdminSessionTest.java
  backend/src/test/java/harustudy/backend/admin/service/AdminAuthServiceTest.java
  backend/src/test/java/harustudy/backend/admin/service/AdminServiceTest.java
  backend/src/test/java/harustudy/backend/study/repository/StudyRepositoryTest.java
Labels: BE, feature

#695 [ALL] 젠킨스 스크립트 체크아웃 스테이지 제거
  jenkins/backend-production.jenkinsfile
  jenkins/backend-production2.jenkinsfile
  jenkins/frontend-admin-develop.jenkinsfile
  jenkins/frontend-admin-production.jenkinsfile
  jenkins/frontend-develop.jenkinsfile
  jenkins/frontend-production.jenkinsfile
Labels: FE, BE, devops

#696 [BE] 인터셉터 설정 변경 및 UUID Column 지정
  backend/src/main/java/harustudy/backend/admin/entity/AdminSession.java
  backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
Labels: BE, feature

#711 [FE] 로그인 및 모달 버그 수정, 스터디 뒤로가기로 나가기 기능 추가
  frontend/src/api/httpInstance.ts
  frontend/src/components/lobby/StudyLobbyContents/StudyLobbyContents.tsx
  frontend/src/components/progress/StudyBoard/StudyBoard.tsx
  frontend/src/components/progress/StudyInfoModal/StudyInfoModal.tsx
  frontend/src/hooks/common/useConfirmBerforeRouting.ts
  frontend/src/utils/Http.ts
Labels: bug, FE, feature

#712 [FE] StudyInfoModal 컴포넌트 errorBoundary 속성 false로 설정
  frontend/src/components/lobby/StudyLobbyContents/StudyLobbyContents.tsx
  frontend/src/components/progress/StudyInfoModal/StudyInfoModal.tsx
Labels: bug, FE

#714 [ALL] 하루스터디 v1.2.1 배포 🎉
  frontend/src/api/httpInstance.ts
  frontend/src/components/lobby/StudyLobbyContents/StudyLobbyContents.tsx
  frontend/src/components/progress/StudyBoard/StudyBoard.tsx
  frontend/src/components/progress/StudyInfoModal/StudyInfoModal.tsx
  frontend/src/hooks/common/useConfirmBerforeRouting.ts
  frontend/src/utils/Http.ts
Labels: release
