Repository woowacourse-teams/2023-haru-study, pull requests merged in 2023-07, with the labels that each got.

#4 [ALL] PR, Discussion 템플릿 추가
  .github/DISCUSSION_TEMPLATE/daily_meeting.yml
  .github/pull-request-template.md
Labels: chore

#9 [FE] webpack 설정 및 초기 개발 세팅
  frontend/.babelrc.json
  frontend/.eslintrc
  frontend/.gitignore
  frontend/.prettierrc
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/jest.config.json
  frontend/jest.setup.ts
  frontend/package.json
  frontend/public/index.html
  frontend/public/mockServiceWorker.js
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/server.ts
  frontend/src/mocks/worker.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: FE, setting

#27 [BE] 스프링 프로젝트 초기 설정
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/harustudy/backend/BackendApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/harustudy/backend/BackendApplicationTests.java
Labels: BE, feature

#25 [BE] CI 워크플로우를 작성한다
  .github/workflows/backend-build-test.yml
Labels: BE, devops

#28 [FE] CI 워크플로우를 작성
  .github/workflows/frontend-build-test.yml
Labels: FE, devops

#30 [BE] ci빌드 환경 셋팅, 결과를 slack알림 추가
  .github/workflows/backend-build-test.yml
Labels: BE, devops

#37 [FE] CI 성공여부 slack 알림 추가
  .github/workflows/frontend-build-test.yml
Labels: FE, devops

#39 [FE] page routing 기본 설정
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/router/index.tsx
  frontend/yarn.lock
Labels: FE, feature, setting

#41 [FE] 스타일 컴포넌트 설정 및 적용
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/.storybook/preview.tsx
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/fonts/SCDream1.otf
  frontend/src/fonts/SCDream2.otf
  frontend/src/fonts/SCDream3.otf
  frontend/src/fonts/SCDream4.otf
  frontend/src/fonts/SCDream5.otf
  frontend/src/fonts/SCDream6.otf
  frontend/src/fonts/SCDream7.otf
  frontend/src/fonts/SCDream8.otf
  frontend/src/fonts/SCDream9.otf
  frontend/src/fonts/font.css
  frontend/src/styles/color.ts
  frontend/src/styles/globalStyle.ts
  frontend/src/styles/reset.ts
  frontend/src/styles/theme.ts
  frontend/src/types/styled-components.d.ts
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: FE, feature, setting

#53 [FE] Typography 템플릿 및 컴포넌트 구현
  frontend/src/App.tsx
  frontend/src/components/common/Typography/Typography.stories.ts
  frontend/src/components/common/Typography/Typography.tsx
Labels: FE, feature, UI

#73 [BE] 엔티티 설계
  backend/build.gradle
  backend/src/main/java/harustudy/backend/entity/Member.java
  backend/src/main/java/harustudy/backend/entity/MemberProgress.java
  backend/src/main/java/harustudy/backend/entity/ParticipantCode.java
  backend/src/main/java/harustudy/backend/entity/Pomodoro.java
  backend/src/main/java/harustudy/backend/entity/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/entity/Study.java
  backend/src/main/java/harustudy/backend/entity/StudyStatus.java
  backend/src/main/java/harustudy/backend/entity/Version.java
  backend/src/main/resources/application.properties
Labels: BE, feature

#69 [BE] 젠킨스 publish over ssh 사용한 배포 파이프라인 구축💪
  jenkinsfiles/backend-prod
Labels: BE, devops

#51 [FE] Button Component 구현
  frontend/.storybook/preview.tsx
  frontend/src/App.tsx
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/CircularProgress/CircularProgress.stories.tsx
  frontend/src/components/common/CircularProgress/CircularProgress.tsx
  frontend/src/constants/style.ts
  frontend/src/styles/color.ts
  frontend/src/styles/theme.ts
  frontend/src/types/style.ts
  frontend/src/types/styled-components.d.ts
Labels: FE, feature, UI

#84 [BE] 모든 엔티티에 등록 시간, 수정 시간 정보 추가
  backend/src/main/java/harustudy/backend/BackendApplication.java
  backend/src/main/java/harustudy/backend/entity/BaseTimeEntity.java
  backend/src/main/java/harustudy/backend/entity/Member.java
  backend/src/main/java/harustudy/backend/entity/MemberProgress.java
  backend/src/main/java/harustudy/backend/entity/MemberRecord.java
  backend/src/main/java/harustudy/backend/entity/ParticipantCode.java
  backend/src/main/java/harustudy/backend/entity/Study.java
Labels: BE, feature

#85 [FE] Input 컴포넌트 구현
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/hooks/useId.ts
  frontend/src/styles/theme.ts
Labels: FE, feature, UI

#87 [FE] 젠킨스 publish over ssh 사용한 배포 파이프라인 구축
  jenkinsfiles/frontend-prod
Labels: FE, devops

#90 [FE] Timer 컴포넌트 구현
  frontend/src/components/Timer/Timer.stories.tsx
  frontend/src/components/Timer/Timer.tsx
  frontend/src/hooks/useTimer.ts
  frontend/webpack.config.js
Labels: FE, feature, UI

#80 [BE] Github Action 빌드 환경 변경 #79
  .github/workflows/backend-build-test.yml
Labels: BE, devops

#98 [FE] 스터디 진행 페이지 사이드바 구현
  frontend/.eslintrc
  frontend/src/components/board/Sidebar/Sidebar.tsx
  frontend/src/components/board/Timer/Timer.stories.tsx
  frontend/src/components/board/Timer/Timer.tsx
  frontend/src/components/common/Typography/Typography.tsx
  frontend/src/hooks/useTimer.ts
  frontend/src/pages/StudyBoard.tsx
  frontend/src/router/index.tsx
Labels: FE, UI

#101 [FE] Select 컴포넌트 구현
  frontend/src/components/common/Select/Select.stories.tsx
  frontend/src/components/common/Select/Select.tsx
  frontend/src/components/common/Select/SelectContext.tsx
  frontend/src/components/common/Select/SelectItem.tsx
  frontend/src/components/common/Select/SelectList.tsx
  frontend/src/components/common/Select/SelectTrigger.tsx
  frontend/src/types/dom.ts
  frontend/src/utils/domEventHandler.ts
Labels: FE, feature, UI

#97 [BE] 스터디 정보 조회 기능 구현
  backend/src/main/java/harustudy/backend/BackendApplication.java
  backend/src/main/java/harustudy/backend/controller/StudyController.java
  backend/src/main/java/harustudy/backend/controller/StudyMemberController.java
  backend/src/main/java/harustudy/backend/dto/MemberContentResponse.java
  backend/src/main/java/harustudy/backend/dto/MemberDto.java
  backend/src/main/java/harustudy/backend/dto/response/CurrentCyclePlanResponse.java
  backend/src/main/java/harustudy/backend/dto/response/MemberContentResponses.java
  backend/src/main/java/harustudy/backend/dto/response/StudyMemberMetaDataResponse.java
  backend/src/main/java/harustudy/backend/dto/response/StudyMetadataResponse.java
  backend/src/main/java/harustudy/backend/entity/MemberProgress.java
  backend/src/main/java/harustudy/backend/entity/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/entity/PomodoroRecord.java
  backend/src/main/java/harustudy/backend/repository/MemberProgressRepository.java
  backend/src/main/java/harustudy/backend/repository/MemberRepository.java
  backend/src/main/java/harustudy/backend/repository/StudyRepository.java
  backend/src/main/java/harustudy/backend/repository/dto/MapStringConverter.java
  backend/src/main/java/harustudy/backend/service/PomodoroProgressService.java
  backend/src/test/java/harustudy/backend/BackendApplicationTests.java
  backend/src/test/java/harustudy/backend/controller/StudyControllerTest.java
  backend/src/test/java/harustudy/backend/integration/FindStudyIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
  backend/src/test/java/harustudy/backend/repository/MemberProgressRepositoryTest.java
  backend/src/test/java/harustudy/backend/service/PomodoroProgressServiceTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/data.sql
Labels: BE, feature

#103 [FE] Menu Component 구현
  frontend/.eslintrc
  frontend/src/assets/icons/HamburgerIcon.tsx
  frontend/src/components/common/Menu/Menu.stories.tsx
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/common/Menu/MenuItem.tsx
  frontend/src/hooks/useOutsideClick.ts
  frontend/src/styles/reset.ts
Labels: FE, feature, UI

#106 [FE] Menu Component Refactoring
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/common/Menu/MenuItem.tsx
Labels: FE, refactor

#110 [BE] 스터디 참여 기능 구현
  backend/src/main/java/harustudy/backend/controller/StudyController.java
  backend/src/main/java/harustudy/backend/dto/request/ParticipateRequest.java
  backend/src/main/java/harustudy/backend/dto/request/StudyAuthRequest.java
  backend/src/main/java/harustudy/backend/dto/response/StudyAuthResponse.java
  backend/src/main/java/harustudy/backend/entity/Member.java
  backend/src/main/java/harustudy/backend/entity/MemberProgress.java
  backend/src/main/java/harustudy/backend/entity/ParticipantCode.java
  backend/src/main/java/harustudy/backend/entity/Pomodoro.java
  backend/src/main/java/harustudy/backend/entity/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/entity/Study.java
  backend/src/main/java/harustudy/backend/exception/DuplicatedNicknameException.java
  backend/src/main/java/harustudy/backend/exception/MemberNameLengthException.java
  backend/src/main/java/harustudy/backend/repository/MemberProgressRepository.java
  backend/src/main/java/harustudy/backend/repository/StudyRepository.java
  backend/src/main/java/harustudy/backend/service/CreatePomodoroStudyService.java
  backend/src/main/java/harustudy/backend/service/ParticipateService.java
  backend/src/main/java/harustudy/backend/service/PomodoroProgressService.java
  backend/src/main/java/harustudy/backend/service/StudyAuthService.java
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/controller/StudyControllerTest.java
  backend/src/test/java/harustudy/backend/entity/MemberTest.java
  backend/src/test/java/harustudy/backend/entity/ParticipantCodeTest.java
  backend/src/test/java/harustudy/backend/entity/PomodoroTest.java
  backend/src/test/java/harustudy/backend/integration/ParticipateStudyIntegrationTest.java
  backend/src/test/java/harustudy/backend/repository/MemberProgressRepositoryTest.java
  backend/src/test/java/harustudy/backend/repository/MemberRecordRepositoryTest.java
  backend/src/test/java/harustudy/backend/service/CreatePomodoroStudyServiceTest.java
  backend/src/test/java/harustudy/backend/service/ParticipateServiceTest.java
  backend/src/test/java/harustudy/backend/service/ProceedPomodoroStudyServiceTest.java
  backend/src/test/java/harustudy/backend/service/StudyAuthServiceTest.java
  backend/src/test/resources/data.sql
Labels: BE, feature

#108 [FE] Study Record MSW 구현
  frontend/src/hooks/useFetch.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/studyRecordHandlers.ts
Labels: FE, feature

#111 [FE] Landing Page 구현
  frontend/__test__/example.test.tsx
  frontend/fileTransformer.js
  frontend/jest.config.json
  frontend/src/App.tsx
  frontend/src/assets/icons/HamburgerIcon.tsx
  frontend/src/assets/image/heroImage.png
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/landing/Contents.tsx
  frontend/src/components/landing/Hero.tsx
  frontend/src/pages/Landing.tsx
  frontend/src/router/index.tsx
  frontend/src/styles/globalStyle.ts
  frontend/src/types/index.d.ts
  frontend/webpack.config.js
Labels: FE, feature, UI

#112 [FE] 스터디 개설 페이지 구현
  frontend/.eslintrc
  frontend/__test__/StudyMakingPage.test.tsx
  frontend/jest.config.json
  frontend/src/api/index.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Select/Select.stories.tsx
  frontend/src/components/common/Select/Select.tsx
  frontend/src/components/common/Select/SelectContext.tsx
  frontend/src/components/common/Select/SelectItem.tsx
  frontend/src/components/common/Select/SelectList.tsx
  frontend/src/components/common/Select/SelectTrigger.tsx
  frontend/src/components/studyMaking/StudyMakingForm/StudyMakingForm.tsx
  frontend/src/components/templates/StudyInfoFormLayout.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/hooks/useStudyMaking.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/studyMakingHandler.ts
  frontend/src/pages/StudyMaking.tsx
  frontend/src/pages/StudyParticipantForHost.tsx
  frontend/src/router/index.tsx
  frontend/tsconfig.paths.json
  frontend/webpack.config.js
Labels: FE, feature, UI

#116 [BE] 스터디 참여시 MemberProgress 영속화 되지 않는 문제 수정
  backend/src/main/java/harustudy/backend/entity/Study.java
  backend/src/test/java/harustudy/backend/service/ParticipateServiceTest.java
Labels: BE, refactor

#119 [BE] 젠킨스 무한 출력 스트림 리다이렉션
  jenkins/backend-prod.jenkinsfile
Labels: BE, devops

#127 [FE] 개설자 참여 페이지 구현
  frontend/.eslintrc
  frontend/src/api/index.ts
  frontend/src/assets/icons/ClipBoardIcon.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/participation/HostParticipationInfo.tsx
  frontend/src/components/studyMaking/StudyMakingForm.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/hooks/useCopyClipBoard.ts
  frontend/src/hooks/useInput.ts
  frontend/src/hooks/useSelect.ts
  frontend/src/hooks/useStudyMaking.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/studyMakingHandler.ts
  frontend/src/mocks/handlers/studyStartHandlers.ts
  frontend/src/pages/StudyMaking.tsx
  frontend/src/pages/StudyParticipantForHost.tsx
  frontend/src/router/index.tsx
  frontend/src/utils/cookie.ts
Labels: FE, feature, UI

#124 [FE] 진행 단계 별 가이드 폼 구현
  frontend/.eslintrc
  frontend/src/assets/icons/CircleCheckIcon.tsx
  frontend/src/components/board/PlanResult/PlanResult.tsx
  frontend/src/components/board/PlanningForm/PlanningForm.tsx
  frontend/src/components/board/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/board/Sidebar/Sidebar.tsx
  frontend/src/components/common/QuestionAnswer/QuestionAnswer.stories.ts
  frontend/src/components/common/QuestionAnswer/QuestionAnswer.tsx
  frontend/src/components/common/QuestionTextarea/QuestionTextarea.stories.ts
  frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx
  frontend/src/hooks/useQuestionTextarea.ts
Labels: FE, feature, UI

#118 [FE] Study Record Page 구현
  frontend/src/assets/icons/CheckRound.tsx
  frontend/src/assets/icons/CycleIcon.tsx
  frontend/src/assets/icons/GoalIcon.tsx
  frontend/src/assets/icons/PencilIcon.tsx
  frontend/src/assets/icons/TimeLineIcon.tsx
  frontend/src/components/common/Accordion/AccordionHeader.tsx
  frontend/src/components/common/Accordion/AccordionSkeleton.tsx
  frontend/src/components/common/Menu/Menu.stories.tsx
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/common/Tabs/TabsSkeleton.tsx
  frontend/src/components/landing/Contents.tsx
  frontend/src/components/landing/Hero.tsx
  frontend/src/components/record/AnswerQuestion.tsx
  frontend/src/components/record/MemberRecord.tsx
  frontend/src/components/record/MemberRecordList.tsx
  frontend/src/components/record/RecordContents.tsx
  frontend/src/components/record/StudyInformation.tsx
  frontend/src/mocks/handlers/studyRecordHandlers.ts
  frontend/src/pages/StudyRecord.tsx
  frontend/src/router/index.tsx
  frontend/src/styles/common.ts
  frontend/webpack.config.js
Labels: FE, feature, UI

#132 [FE] Record Page $ prefix 추가
  frontend/src/components/common/Tabs/TabList.tsx
  frontend/src/components/record/AnswerQuestion.tsx
  frontend/src/components/record/RecordContents.tsx
  frontend/src/components/record/StudyInformation.tsx
Labels: bug, FE

#125 [BE] 스웨거 적용
  backend/build.gradle
  backend/src/main/resources/application.yml
Labels: BE, feature

#135 [BE] 스터디 멤버 등록 후 첫 계획 작성 시 member_content가 생성되지 않는 문제
  backend/src/main/java/harustudy/backend/content/domain/PomodoroContent.java
  backend/src/main/java/harustudy/backend/content/service/ContentService.java
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/room/domain/Room.java
  backend/src/main/java/harustudy/backend/room/service/RoomService.java
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/participantcode/service/ParticipantCodeServiceTest.java
  backend/src/test/java/harustudy/backend/room/service/RoomServiceTest.java
Labels: BE, feature

#143 [BE] Flyway Mysql 의존성 추가
  backend/build.gradle
Labels: BE, feature

#150 [BE] template version 삭제
  backend/src/main/java/harustudy/backend/content/domain/PomodoroContent.java
  backend/src/main/java/harustudy/backend/content/domain/TemplateVersion.java
  backend/src/main/resources/db/migration/V1.1__delete-template-version.sql
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/content/repository/MemberContentRepositoryTest.java
  backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
  backend/src/test/java/harustudy/backend/progress/service/ProgressServiceTest.java
Labels: BE, refactor

#136 [FE] 스터디 참여 페이지 구현
  frontend/.eslintrc
  frontend/src/api/index.ts
  frontend/src/components/landing/Contents.tsx
  frontend/src/components/participation/HostParticipationInfo.tsx
  frontend/src/components/participation/ParticipationInfo/NickNameExistence.tsx
  frontend/src/components/participation/ParticipationInfo/NickNameNonExistence.tsx
  frontend/src/components/participation/ParticipationInfo/ParticipationInfo.tsx
  frontend/src/components/studyMaking/StudyMakingForm.tsx
  frontend/src/hooks/fetch/useParticipantCode.ts
  frontend/src/hooks/fetch/useParticipateStudy.ts
  frontend/src/mocks/handlers/checkParticipantCodeHandlers.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/studyMakingHandler.ts
  frontend/src/mocks/handlers/studyStartHandlers.ts
  frontend/src/pages/StudyParticipant.tsx
  frontend/src/router/index.tsx
  frontend/webpack.config.js
Labels: FE, feature, UI

#149 [FE] 스터디 진행 페이지 구현
  frontend/src/components/board/GuideContents/GuideContents.tsx
  frontend/src/components/board/PlanResult/PlanResult.tsx
  frontend/src/components/board/PlanningForm/PlanningForm.tsx
  frontend/src/components/board/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/board/Sidebar/Sidebar.tsx
  frontend/src/components/board/StudyingForm/StudyingForm.tsx
  frontend/src/components/board/Timer/Timer.stories.tsx
  frontend/src/components/board/Timer/Timer.tsx
  frontend/src/components/common/QuestionAnswer/QuestionAnswer.tsx
  frontend/src/hooks/board/usePlanningForm.ts
  frontend/src/hooks/board/useRetrospectForm.ts
  frontend/src/hooks/board/useStudyBoard.ts
  frontend/src/hooks/board/useStudyingForm.ts
  frontend/src/hooks/useQuestionTextarea.ts
  frontend/src/hooks/useTimer.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/studyBoardHandler.ts
  frontend/src/pages/StudyBoard.tsx
  frontend/src/types/study.ts
Labels: FE, feature, UI

#154 [ALL] 잘못된 api url 수정 및 진행 페이지 라우팅 버그 수정
  frontend/src/api/index.ts
  frontend/src/components/board/RetrospectForm/RetrospectForm.tsx
Labels: bug, FE

#156 [BE] 메타데이터 step을 소문자로 변경해서 반환한도록 변경
  backend/src/main/java/harustudy/backend/progress/dto/RoomAndProgressStepResponse.java
  backend/src/test/java/harustudy/backend/progress/service/ProgressServiceTest.java
Labels: BE, refactor

#158 [FE] MemberContent type refactoring
  frontend/src/components/record/MemberRecord.tsx
  frontend/src/mocks/handlers/studyRecordHandlers.ts
Labels: FE, refactor

#161 [FE] 개설하기 요청 버그
  frontend/src/api/index.ts
  frontend/src/components/studyMaking/StudyMakingForm.tsx
  frontend/src/hooks/board/usePlanningForm.ts
  frontend/src/hooks/board/useRetrospectForm.ts
  frontend/src/hooks/board/useStudyingForm.ts
Labels: bug, FE

#164 [FE] 학습 목표, 개설하기, 참여하기 api 데이터 형식 수정
  frontend/src/api/index.ts
  frontend/src/components/board/GuideContents/GuideContents.tsx
  frontend/src/components/board/StudyingForm/StudyingForm.tsx
  frontend/src/hooks/board/useStudyingForm.ts
Labels: bug, FE

#165 [BE] 스웨거 ip 설정
  backend/src/main/java/harustudy/backend/config/OpenApiConfiguration.java
Labels: BE, feature

#168 [FE] 참여 코드 인증 api 요청 로직 수정
  frontend/src/hooks/fetch/useParticipantCode.ts
  frontend/src/mocks/handlers/checkParticipantCodeHandlers.ts
Labels: bug, FE

#169 [BE] 현재 사이클 조회 응답 수정
  backend/src/main/java/harustudy/backend/config/OpenApiConfiguration.java
  backend/src/main/java/harustudy/backend/content/controller/ContentController.java
  backend/src/main/java/harustudy/backend/content/dto/CurrentCyclePlanResponse.java
  backend/src/main/java/harustudy/backend/content/service/ContentService.java
  backend/src/test/java/harustudy/backend/integration/FindRoomIntegrationTest.java
  backend/src/test/java/harustudy/backend/progress/service/ProgressServiceTest.java
Labels: BE, refactor

#180 [FE] 스토리북 배포
  frontend/.gitignore
  jenkins/frontend-prod.jenkinsfile
Labels: FE, devops

#183 [FE] 스토리북 배포 스크립트 오탈자 수정
  jenkins/frontend-prod.jenkinsfile
Labels: FE, devops

#182 [FE] 스터디 진행페이지 학습 단계 목표 순서 다르게 나오는 문제
  frontend/src/components/board/StudyingForm/StudyingForm.tsx
Labels: bug, FE

#188 [FE] 스터디 참여 페이지 리팩터링
  frontend/src/components/participation/HostParticipationInfo.tsx
  frontend/src/components/participation/ParticipationInfo/ParticipationInfo.tsx
  frontend/src/components/preparation/MemberRegister/MemberRegister.tsx
  frontend/src/components/preparation/MemberRestart/MemberRestart.tsx
  frontend/src/components/preparation/ParticipationCodeCopier/ParticipationCodeCopier.tsx
  frontend/src/components/preparation/ParticipationCodeInput/ParticipationCodeInput.tsx
  frontend/src/components/studyMaking/StudyMakingForm.tsx
  frontend/src/hooks/fetch/useParticipantCode.ts
  frontend/src/hooks/fetch/useParticipateStudy.ts
  frontend/src/mocks/handlers/checkParticipantCodeHandlers.ts
  frontend/src/mocks/handlers/studyStartHandlers.ts
  frontend/src/pages/StudyParticipant.tsx
  frontend/src/pages/StudyParticipantForHost.tsx
  frontend/src/pages/StudyPreparation.tsx
  frontend/src/router/index.tsx
Labels: FE, refactor

#190 [FE] 스토리북 배포 스크립트 실행시키는 젠킨스 스크립트 작성
  jenkins/frontend-prod.jenkinsfile
Labels: FE, devops

#192 [BE] 멤버 생성시 ID 반환하지 않는 문제 수정
  backend/src/main/java/harustudy/backend/room/controller/RoomController.java
Labels: bug, BE, refactor

#194 [FE] 스터디 참여시 Content-Type 추가
  frontend/src/components/preparation/ParticipationCodeInput/ParticipationCodeInput.tsx
Labels: FE, refactor

#201 [BE] 한 사이클의 스터디가 종료되었을 때 사이클 수가 늘어나지 않는 문제
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
  backend/src/test/java/harustudy/backend/progress/domain/PomodoroProgressTest.java
Labels: BE, feature

#202 [BE] 스터디 최대 진행 시간 40분에서 60분으로 변경
  backend/src/main/java/harustudy/backend/room/domain/PomodoroRoom.java
  backend/src/main/java/harustudy/backend/room/dto/CreatePomodoroRoomRequest.java
  backend/src/test/java/harustudy/backend/room/controller/ParticipantCodeControllerTest.java
  backend/src/test/java/harustudy/backend/room/domain/PomodoroRoomTest.java
Labels: bug, BE, feature

#206 [FE] alert 메시지 띄어쓰기 수정
  frontend/src/hooks/board/usePlanningForm.ts
Labels: bug, FE

#208 [FE] 라우터 상수화
  frontend/__test__/StudyMakingPage.test.tsx
  frontend/src/components/board/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/board/StudyingForm/StudyingForm.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/landing/Contents.tsx
  frontend/src/components/preparation/MemberRegister/MemberRegister.tsx
  frontend/src/components/preparation/MemberRestart/MemberRestart.tsx
  frontend/src/components/preparation/ParticipationCodeInput/ParticipationCodeInput.tsx
  frontend/src/components/studyMaking/StudyMakingForm.tsx
  frontend/src/constants/routes.ts
  frontend/src/pages/CreateStudy.tsx
  frontend/src/pages/StudyBoard.tsx
  frontend/src/pages/StudyParticipant.tsx
  frontend/src/router/index.tsx
Labels: FE, refactor

#209 [FE] 폴더 구조 변경
  frontend/.eslintrc
  frontend/__test__/example.test.tsx
  frontend/src/components/board/Timer/Timer.tsx
  frontend/src/components/common/Accordion/AccordionContext.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/common/Select/Select.tsx
  frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
  frontend/src/components/landing/Hero/Hero.tsx
  frontend/src/components/landing/LandingContents/LandingContents.tsx
  frontend/src/components/preparation/MemberRegister/MemberRegister.tsx
  frontend/src/components/preparation/ParticipationCodeCopier/ParticipationCodeCopier.tsx
  frontend/src/components/preparation/ParticipationCodeInput/ParticipationCodeInput.tsx
  frontend/src/components/record/AnswerQuestion/AnswerQuestion.tsx
  frontend/src/components/record/MemberRecord/MemberRecord.tsx
  frontend/src/components/record/MemberRecordList/MemberRecordList.tsx
  frontend/src/components/record/RecordContents/RecordContents.tsx
  frontend/src/components/record/StudyInformation/StudyInformation.tsx
  frontend/src/hooks/api/useFetch.ts
  frontend/src/hooks/board/usePlanningForm.ts
  frontend/src/hooks/board/useRetrospectForm.ts
  frontend/src/hooks/board/useTimer.ts
  frontend/src/hooks/common/useClipBoard.ts
  frontend/src/hooks/common/useDisplay.ts
  frontend/src/hooks/common/useId.ts
  frontend/src/hooks/common/useInput.ts
  frontend/src/hooks/common/useOutsideClick.ts
  frontend/src/hooks/common/useQuestionTextarea.ts
  frontend/src/hooks/common/useSelect.ts
  frontend/src/pages/CreateStudy.tsx
  frontend/src/pages/Landing.tsx
  frontend/src/pages/StudyParticipant.tsx
  frontend/src/pages/StudyPreparation.tsx
  frontend/src/pages/StudyRecord.tsx
  frontend/src/pages/layout/StudyPreparationLayout.tsx
Labels: FE, refactor

#213 [FE] eslint type import 적용 및 alias 순서 변경
  frontend/.eslintrc
  frontend/src/components/board/GuideContents/GuideContents.tsx
  frontend/src/components/board/Sidebar/Sidebar.tsx
  frontend/src/components/board/StudyingForm/StudyingForm.tsx
  frontend/src/components/board/Timer/Timer.tsx
  frontend/src/components/common/Accordion/Accordion.tsx
  frontend/src/components/common/Accordion/AccordionContext.tsx
  frontend/src/components/common/Accordion/AccordionHeader.tsx
  frontend/src/components/common/Accordion/AccordionItem.tsx
  frontend/src/components/common/Accordion/AccordionPanel.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/CircularProgress/CircularProgress.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/common/Menu/MenuItem.tsx
  frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx
  frontend/src/components/common/Select/Select.tsx
  frontend/src/components/common/Select/SelectItem.tsx
  frontend/src/components/common/Select/SelectList.tsx
  frontend/src/components/common/Select/SelectTrigger.tsx
  frontend/src/components/common/Tabs/TabItem.tsx
  frontend/src/components/common/Tabs/Tabs.tsx
  frontend/src/components/common/Tabs/TabsContext.tsx
  frontend/src/components/common/Typography/Typography.tsx
  frontend/src/hooks/board/useStudyBoard.ts
  frontend/src/hooks/board/useStudyingForm.ts
  frontend/src/utils/domEventHandler.ts
Labels: FE, refactor

#215 [BE] 데이터베이스 스키마 및 엔티티 구조 변경
  backend/src/main/java/harustudy/backend/content/controller/PomodoroContentController.java
  backend/src/main/java/harustudy/backend/content/domain/MemberContent.java
  backend/src/main/java/harustudy/backend/content/domain/PomodoroContent.java
  backend/src/main/java/harustudy/backend/content/dto/MemberContentResponse.java
  backend/src/main/java/harustudy/backend/content/dto/MemberContentResponses.java
  backend/src/main/java/harustudy/backend/content/dto/PomodoroContentResponse.java
  backend/src/main/java/harustudy/backend/content/dto/PomodoroContentResponses.java
  backend/src/main/java/harustudy/backend/content/repository/ContentRepository.java
  backend/src/main/java/harustudy/backend/content/repository/PomodoroContentRepository.java
  backend/src/main/java/harustudy/backend/content/service/PomodoroContentService.java
  backend/src/main/java/harustudy/backend/member/controller/MemberController.java
  backend/src/main/java/harustudy/backend/member/domain/Member.java
  backend/src/main/java/harustudy/backend/member/service/MemberService.java
  backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
  backend/src/main/java/harustudy/backend/participantcode/service/ParticipantCodeService.java
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
  backend/src/main/java/harustudy/backend/progress/domain/MemberProgress.java
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/progress/dto/RoomAndProgressStepResponse.java
  backend/src/main/java/harustudy/backend/progress/exception/InvalidPomodoroProgressException.java
  backend/src/main/java/harustudy/backend/progress/exception/InvalidProgressException.java
  backend/src/main/java/harustudy/backend/progress/exception/StudyPomodoroProgressException.java
  backend/src/main/java/harustudy/backend/progress/exception/StudyProgressException.java
  backend/src/main/java/harustudy/backend/progress/repository/MemberProgressRepository.java
  backend/src/main/java/harustudy/backend/progress/repository/PomodoroProgressRepository.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomController.java
  backend/src/main/java/harustudy/backend/room/controller/RoomController.java
  backend/src/main/java/harustudy/backend/room/domain/PomodoroRoom.java
  backend/src/main/java/harustudy/backend/room/domain/Room.java
  backend/src/main/java/harustudy/backend/room/dto/CreatePomodoroRoomDto.java
  backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomAndMembersResponse.java
  backend/src/main/java/harustudy/backend/room/dto/RoomAndMembersResponse.java
  backend/src/main/java/harustudy/backend/room/exception/PomodoroRoomNameLengthException.java
  backend/src/main/java/harustudy/backend/room/exception/RoomNameLengthException.java
  backend/src/main/java/harustudy/backend/room/repository/PomodoroRoomRepository.java
  backend/src/main/java/harustudy/backend/room/repository/RoomRepository.java
  backend/src/main/java/harustudy/backend/room/service/PomodoroRoomService.java
  backend/src/main/resources/db/migration/V1.0__init.sql
  backend/src/main/resources/db/migration/V1.1__delete-template-version.sql
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/content/repository/MemberPomodoroContentRepositoryTest.java
  backend/src/test/java/harustudy/backend/content/service/PomodoroContentServiceTest.java
  backend/src/test/java/harustudy/backend/integration/AuthenticateIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/FindRoomIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ParticipateRoomIntegrationTest.java
  backend/src/test/java/harustudy/backend/participantcode/service/ParticipantCodeServiceTest.java
  backend/src/test/java/harustudy/backend/progress/repository/PomodoroProgressRepositoryTest.java
  backend/src/test/java/harustudy/backend/progress/service/PomodoroProgressServiceTest.java
  backend/src/test/java/harustudy/backend/room/domain/PomodoroRoomTest.java
  backend/src/test/java/harustudy/backend/room/service/CreatePomodoroPomodoroRoomServiceTest.java
  backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceTest.java
Labels: BE, refactor

#217 [FE] 스토리북 배포 젠킨스 스크립트 수정
  jenkins/frontend-prod.jenkinsfile
Labels: FE, devops

#219 [BE] MySQL Dialect 적용
  backend/src/main/resources/db/migration/V1.0__init.sql
Labels: BE, refactor

#221 [BE] init.sql 오류 수정
  backend/src/main/resources/db/migration/V1.0__init.sql
Labels: BE, refactor
