Repository woowacourse-teams/2023-haru-study, pull requests merged in 2023-11, with the labels that each got.

#719 [BE] 여러개의 쿼리파라미터를 ModelAttribute로 변경
  backend/src/main/java/harustudy/backend/study/controller/StudyController.java
  backend/src/main/java/harustudy/backend/study/dto/StudyFilterRequest.java
  backend/src/main/java/harustudy/backend/study/service/StudyService.java
  backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
Labels: BE, refactor

#718 [BE] 불필요한 코드 제거 및 리팩터링 (@EnableScheduling 제거)
  backend/src/main/java/harustudy/backend/HaruStudyApplication.java
Labels: BE, refactor

#704 [BE] 어드민 페이지 참여코드 조회 버그 개선
  backend/src/main/java/harustudy/backend/admin/controller/AdminController.java
  backend/src/main/java/harustudy/backend/admin/dto/AdminParticipantCodesResponse.java
  backend/src/main/java/harustudy/backend/admin/service/AdminService.java
  backend/src/main/java/harustudy/backend/view/dto/CalendarStudyRecordsResponse.java
  backend/src/main/java/harustudy/backend/view/dto/StudyRecordsPageResponse.java
  backend/src/main/java/harustudy/backend/view/service/ViewService.java
  backend/src/test/java/harustudy/backend/admin/service/AdminServiceTest.java
Labels: BE, refactor

#707 [BE] 방장 권한 검사 로직 추가
  backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/participant/domain/Participant.java
  backend/src/main/java/harustudy/backend/participant/exception/ParticipantIsNotHostException.java
  backend/src/main/java/harustudy/backend/study/service/StudyService.java
  backend/src/test/java/harustudy/backend/study/repository/StudyRepositoryTest.java
  backend/src/test/java/harustudy/backend/study/service/StudyServiceTest.java
Labels: BE, feature

#716 [BE] 불필요한 코드 제거 및 리팩터링
  backend/src/main/java/harustudy/backend/HaruStudyApplication.java
  backend/src/main/java/harustudy/backend/polling/controller/PollingController.java
  backend/src/main/java/harustudy/backend/study/controller/StudyController.java
  backend/src/main/java/harustudy/backend/study/dto/StudyFilterRequest.java
  backend/src/main/java/harustudy/backend/study/service/StudyService.java
  backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
Labels: BE, refactor

#717 [BE] 코드 스타일 조정 및 리팩토링
  backend/src/main/java/harustudy/backend/admin/AdminInterceptor.java
  backend/src/main/java/harustudy/backend/admin/entity/Admin.java
  backend/src/main/java/harustudy/backend/admin/service/AdminAuthService.java
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
  backend/src/main/java/harustudy/backend/auth/dto/RefreshTokenRequest.java
  backend/src/main/java/harustudy/backend/auth/dto/TokenResponse.java
  backend/src/main/java/harustudy/backend/auth/service/AuthService.java
  backend/src/main/java/harustudy/backend/common/CachingFilter.java
  backend/src/main/java/harustudy/backend/common/LoggingInterceptor.java
  backend/src/main/java/harustudy/backend/content/domain/Content.java
  backend/src/main/java/harustudy/backend/content/service/ContentService.java
  backend/src/main/java/harustudy/backend/member/domain/Member.java
  backend/src/main/java/harustudy/backend/member/repository/MemberRepository.java
  backend/src/main/java/harustudy/backend/participant/domain/Participant.java
  backend/src/main/java/harustudy/backend/participant/repository/ParticipantRepository.java
  backend/src/main/java/harustudy/backend/participant/service/ParticipantService.java
  backend/src/main/java/harustudy/backend/study/domain/Study.java
  backend/src/test/java/harustudy/backend/admin/service/AdminServiceTest.java
  backend/src/test/java/harustudy/backend/content/repository/ContentRepositoryTest.java
  backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java
  backend/src/test/java/harustudy/backend/integration/ContentIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/MemberIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ParticipantIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/PollingIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ViewIntegrationTest.java
  backend/src/test/java/harustudy/backend/participant/domain/ParticipantTest.java
  backend/src/test/java/harustudy/backend/participant/service/ParticipantServiceTest.java
  backend/src/test/java/harustudy/backend/polling/service/PollingServiceTest.java
  backend/src/test/java/harustudy/backend/study/service/StudyServiceTest.java
  backend/src/test/java/harustudy/backend/view/service/ViewServiceTest.java
Labels: BE, refactor

#726 [BE] CI에서 사용하지 않는 workflow_dispatch 내용 제거 #722
  .github/workflows/backend-build-test.yml
Labels: devops

#724 [BE] 서비스 중복 로직 제거 및 캡슐화
  backend/src/main/java/harustudy/backend/content/service/ContentService.java
  backend/src/main/java/harustudy/backend/participant/domain/Participant.java
  backend/src/main/java/harustudy/backend/participant/repository/ParticipantRepository.java
  backend/src/main/java/harustudy/backend/participant/service/ParticipantService.java
  backend/src/main/java/harustudy/backend/polling/controller/PollingController.java
  backend/src/main/java/harustudy/backend/polling/service/PollingService.java
  backend/src/main/java/harustudy/backend/study/domain/Study.java
  backend/src/main/java/harustudy/backend/study/repository/StudyRepository.java
  backend/src/main/java/harustudy/backend/study/service/StudyService.java
  backend/src/main/java/harustudy/backend/view/service/ViewService.java
Labels: BE, refactor

#741 [BE] 로깅 파일 저장 경로 변경
  backend/src/main/resources/console-appender.xml
  backend/src/main/resources/logback-spring.xml
Labels: BE, feature

#740 [FE] cd용 github action workflow 추가
  .github/workflows/frontend-develop-deploy.yml
  .github/workflows/frontend-main-deploy.yml
Labels: FE, devops

#743 [BE] 백엔드 Github Action CD 구현
  .github/workflows/backend-deploy.yml
  .github/workflows/frontend-develop-deploy.yml
  .github/workflows/frontend-main-deploy.yml
Labels: BE, devops

#749 [FE] github action submodule 설정 추가
  .github/workflows/frontend-develop-deploy.yml
  .github/workflows/frontend-main-deploy.yml
Labels: FE, devops

#752 [FE] 프론트 워크플로우 경로 변경
  .github/workflows/frontend-develop-deploy.yml
  .github/workflows/frontend-main-deploy.yml
Labels: devops

#755 [FE] frontend cd scp strip components level 수정
  .github/workflows/frontend-develop-deploy.yml
  .github/workflows/frontend-main-deploy.yml
Labels: devops
