Repository woowacourse-teams/2023-haru-study, pull requests merged in 2023-09, with the labels that each got.

#455 [BE] 참여 코드 관련 서비스를 만료 가능한 버전으로 변경
  backend/src/main/java/harustudy/backend/config/BeanConfig.java
  backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
  backend/src/main/java/harustudy/backend/room/domain/CodeGenerationStrategy.java
  backend/src/main/java/harustudy/backend/room/domain/GenerationStrategy.java
  backend/src/main/java/harustudy/backend/room/domain/ParticipantCode.java
  backend/src/main/java/harustudy/backend/room/domain/PomodoroRoom.java
  backend/src/main/java/harustudy/backend/room/dto/CreatePomodoroRoomResponse.java
  backend/src/main/java/harustudy/backend/room/repository/ParticipantCodeRepository.java
  backend/src/main/java/harustudy/backend/room/repository/PomodoroRoomRepository.java
  backend/src/main/java/harustudy/backend/room/service/PomodoroRoomService.java
  backend/src/test/java/harustudy/backend/content/repository/PomodoroContentRepositoryTest.java
  backend/src/test/java/harustudy/backend/content/service/PomodoroContentServiceTest.java
  backend/src/test/java/harustudy/backend/integration/MemberIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/PomodoroContentIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/PomodoroProgressIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/PomodoroRoomIntegrationTest.java
  backend/src/test/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepositoryTest.java
  backend/src/test/java/harustudy/backend/progress/domain/PomodoroProgressTest.java
  backend/src/test/java/harustudy/backend/progress/repository/PomodoroProgressRepositoryTest.java
  backend/src/test/java/harustudy/backend/progress/service/PomodoroProgressServiceTest.java
  backend/src/test/java/harustudy/backend/room/domain/CodeGenerationStrategyTest.java
  backend/src/test/java/harustudy/backend/room/domain/ParticipantCodeTest.java
  backend/src/test/java/harustudy/backend/room/domain/PomodoroRoomTest.java
  backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceTest.java
Labels: BE, feature

#458 [FE] Http 클래스 구현 및 기타 사항 리팩토링
  frontend/src/api/httpInstance.ts
  frontend/src/api/index.ts
  frontend/src/errors/index.ts
  frontend/src/utils/cookie.ts
  frontend/src/utils/http2.ts
  frontend/src/utils/params.ts
  frontend/src/utils/tokenStorage.ts
Labels: FE, refactor

#462 [FE] 스터디 기록 및 멤버 정보 불러오기 API 리팩터링
  frontend/src/api/httpInstance.ts
  frontend/src/api/index.ts
  frontend/src/components/record/MemberRecordContents/MemberRecordContents.tsx
  frontend/src/components/record/ProgressRecord/ProgressRecord.tsx
  frontend/src/components/record/StudyRecordContents/StudyRecordContents.tsx
  frontend/src/contexts/MemberInfoProvider.tsx
  frontend/src/hooks/record/useMemberRecord.ts
  frontend/src/hooks/record/useProgressRecord.ts
  frontend/src/hooks/record/useStudyRecord.ts
  frontend/src/pages/Auth.tsx
Labels: FE, refactor

#469 [FE] 스터디 대기 인원 컴포넌트 UI 구현
  frontend/src/components/waiting/StudyWaitingMembers/StudyWaitingMembers.tsx
  frontend/src/components/waiting/StudyWaitingMembers/StudyWaitingMemebers.stories.tsx
Labels: FE, UI

#460 [BE] 에러코드 명세 페이지 API Path 수정
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
  backend/src/main/java/harustudy/backend/common/exception/ErrorCodeView.java
Labels: BE, feature

#485 [BE] 에러코드 페이지에서는 Interceptor가 작동하지 않도록 수정
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
  backend/src/main/java/harustudy/backend/auth/exception/RefreshTokenNotExistsException.java
  backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
Labels: BE, feature

#488 [BE] 정적 자원을 찾을 수 있도록 경로 매핑
  backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
  backend/src/main/resources/templates/error-code.html
Labels: BE, feature

#490 [BE] progress 조회 시 없으면 null을 반환하는 임시 API 생성
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
Labels: BE, feature

#496 [ALL] README를 추가한다
  README.md
Labels: documentation

#499 [BE] Oauth 로그인 외부 API 호출 로직 분리 및 읽기 전용 트랜잭션 적용
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
  backend/src/main/java/harustudy/backend/auth/service/AuthService.java
  backend/src/main/java/harustudy/backend/auth/service/OauthLoginFacade.java
  backend/src/main/java/harustudy/backend/content/service/PomodoroContentService.java
  backend/src/main/java/harustudy/backend/member/controller/MemberController.java
  backend/src/main/java/harustudy/backend/member/service/MemberService.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
  backend/src/main/java/harustudy/backend/study/service/PomodoroStudyService.java
  backend/src/test/java/harustudy/backend/auth/service/AuthServiceTest.java
  backend/src/test/java/harustudy/backend/member/service/MemberServiceTest.java
Labels: BE, feature

#500 [FE] 진행 페이지 리팩토링 및 Error Boundary, fetch 훅 구현
  frontend/.eslintrc
  frontend/src/App.tsx
  frontend/src/api/httpInstance.ts
  frontend/src/assets/icons/CycleIcon.tsx
  frontend/src/assets/icons/ResetIcon.tsx
  frontend/src/components/board/StepContents/StepContents.tsx
  frontend/src/components/common/AlertErrorBoundary/AlertErrorBoundary.tsx
  frontend/src/components/common/ErrorFallback/ErrorFallback.tsx
  frontend/src/components/common/GlobalErrorBoundary/GlobalErrorBoundary.tsx
  frontend/src/components/participation/MemberRegister/MemberRegister.tsx
  frontend/src/components/participation/MemberRestart/MemberRestart.tsx
  frontend/src/components/progress/GuideModal/GuideModal.tsx
  frontend/src/components/progress/PlanningForm/PlanningForm.tsx
  frontend/src/components/progress/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/progress/Sidebar/Sidebar.tsx
  frontend/src/components/progress/StudyBoard/StudyBoard.tsx
  frontend/src/components/progress/StudyingForm/StudyingForm.tsx
  frontend/src/components/progress/Timer/Timer.stories.tsx
  frontend/src/components/progress/Timer/Timer.tsx
  frontend/src/components/progress/hooks/usePlanningForm.ts
  frontend/src/components/progress/hooks/useRetrospectForm.ts
  frontend/src/components/progress/hooks/useStudyBoard.ts
  frontend/src/components/progress/hooks/useStudyingForm.ts
  frontend/src/components/progress/hooks/useTimer.ts
  frontend/src/constants/routes.ts
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/contexts/StudyProgressProvider.tsx
  frontend/src/errors/index.ts
  frontend/src/hooks/api/useFetch.ts
  frontend/src/hooks/api/useMutation.ts
  frontend/src/pages/StudyBoard.tsx
  frontend/src/pages/StudyProgress.tsx
  frontend/src/pages/layout/LoadingLayout.tsx
  frontend/src/router/index.tsx
  frontend/src/utils/Http.ts
Labels: FE, refactor

#511 [BE] interceptor와 sse관련 로깅 문제 해결
  backend/src/main/java/harustudy/backend/common/CachingFilter.java
  backend/src/main/java/harustudy/backend/config/FilterConfig.java
Labels: BE, feature

#517 [FE] MemberInfoProvider 로직 수정 및 useFetch, useMutation 옵션 추가
  frontend/.eslintrc
  frontend/src/App.tsx
  frontend/src/components/progress/hooks/useStudyBoard.ts
  frontend/src/contexts/MemberInfoProvider.tsx
  frontend/src/contexts/StudyProgressProvider.tsx
  frontend/src/hooks/api/useFetch.ts
  frontend/src/hooks/api/useMutation.ts
Labels: FE, refactor

#518 [FE] 기록 페이지 useFetch, errorBoundary 적용
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/components/record/MemberRecordContents/MemberRecordContents.tsx
  frontend/src/components/record/MemberRecordList/MemberRecordList.tsx
  frontend/src/components/record/MemberRecordList/MemberRecordListSkeleton.tsx
  frontend/src/components/record/ProgressRecord/ProgressRecord.tsx
  frontend/src/components/record/ProgressRecordList/ProgressRecordList.tsx
  frontend/src/components/record/ResetButton/ResetButton.tsx
  frontend/src/components/record/StudyInformation/StudyInformation.tsx
  frontend/src/components/record/StudyInformation/StudyInformationSkeleton.tsx
  frontend/src/components/record/StudyInformation/style.ts
  frontend/src/components/record/StudyRecordContents/StudyRecordContents.tsx
  frontend/src/components/record/hooks/useMemberRecordContents.ts
  frontend/src/components/record/hooks/useMemberStudyListData.ts
  frontend/src/components/record/hooks/useStudyData.ts
  frontend/src/components/record/hooks/useStudyMembers.ts
  frontend/src/hooks/api/useFetch.ts
  frontend/src/hooks/record/useMemberRecord.ts
  frontend/src/hooks/record/useProgressRecord.ts
  frontend/src/hooks/record/useStudyRecord.ts
  frontend/src/mocks/handlers/studyRecordHandlers.ts
  frontend/src/pages/layout/RecordLayout.tsx
  frontend/yarn.lock
Labels: FE, refactor

#524 [FE] 랜딩 페이지 토큰 에러 수정 및 구글 애널리틱스 태그 삽입
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/api/httpInstance.ts
  frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
  frontend/src/components/common/GlobalErrorBoundary/GlobalErrorBoundary.tsx
  frontend/src/components/landing/LandingButton/LandingButton.tsx
  frontend/src/contexts/MemberInfoProvider.tsx
  frontend/src/hooks/api/useFetch.ts
  frontend/src/hooks/api/useMutation.ts
  frontend/src/pages/Auth.tsx
  frontend/src/utils/getUrlQuery.ts
  frontend/src/utils/url.ts
Labels: bug, FE, feature, refactor

#520 [FE] 개설하기, 참여하기, 준비하기 페이지 반응형 작업
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/pages/layout/StudyParticipationLayout.tsx
Labels: FE, UI

#530 [FE] 개설하기, 참여하기, 준비하기 반응형 작업 v2
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Select/Select.tsx
  frontend/src/components/common/Select/SelectItem.tsx
  frontend/src/components/common/Select/SelectTrigger.tsx
  frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
  frontend/src/components/participation/ParticipationCodeInput/ParticipationCodeInput.tsx
  frontend/src/components/participation/PrticipationContents/MemberRegister/MemberRegister.tsx
  frontend/src/components/participation/PrticipationContents/MemberRestart/MemberRestart.tsx
  frontend/src/components/participation/PrticipationContents/ParticipationCodeCopier/ParticipationCodeCopier.tsx
  frontend/src/pages/layout/StudyParticipationLayout.tsx
Labels: FE, refactor, UI

#535 [FE] 타이머 기능 추가
  frontend/public/sounds/alarm-digital.mp3
  frontend/src/components/common/Select/SelectList.tsx
  frontend/src/components/progress/Timer/Timer.tsx
  frontend/src/components/progress/hooks/useStepTimer.ts
  frontend/src/components/progress/hooks/useTimer.ts
  frontend/src/components/record/MemberRecordList/MemberRecordList.tsx
  frontend/src/components/record/StudyInformation/StudyInformation.tsx
  frontend/src/hooks/common/useTimer.ts
  frontend/src/types/dom.ts
  frontend/src/utils/audioPlayer.ts
  frontend/src/utils/date.ts
  frontend/src/utils/dom.ts
  frontend/src/utils/domEventHandler.ts
  frontend/src/utils/format.ts
Labels: FE, feature

#534 [FE] 하루스터디 카카오톡 오픈카톡방으로 이동하기
  frontend/__test__/LandingPage.test.tsx
  frontend/src/assets/icons/ChatIcon.tsx
  frontend/src/assets/icons/ReportIon.tsx
  frontend/src/components/landing/BugReportingLink/BugReportingLink.tsx
  frontend/src/components/landing/ChattingLink/ChattingLink.tsx
  frontend/src/components/landing/GuideSection/GuideSection.tsx
  frontend/src/components/landing/SideLink/SideLik.tsx
  frontend/src/components/landing/StartSection/StartSection.tsx
  frontend/src/components/landing/StudyEffectGuide/StudyEffectGuide.tsx
  frontend/src/pages/Landing.tsx
  frontend/src/styles/color.ts
Labels: FE, feature, UI

#539 [FE] 로그인 페이지(Auth) 요청 순서 보장하지 못하는 버그
  frontend/src/api/httpInstance.ts
  frontend/src/contexts/MemberInfoProvider.tsx
Labels: bug, FE

#540 [FE] 프론트엔드 성능 개선
  frontend/.gitignore
  frontend/__test__/StudyPreparationPage.test.tsx
  frontend/package.json
  frontend/public/fonts/Pretendard-Bold.woff
  frontend/public/fonts/Pretendard-Bold.woff2
  frontend/public/fonts/Pretendard-Light.woff
  frontend/public/fonts/Pretendard-Light.woff2
  frontend/public/fonts/Pretendard-Medium.woff
  frontend/public/fonts/Pretendard-Medium.woff2
  frontend/public/fonts/font.css
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/image/heroImage.png
  frontend/src/assets/image/planningStep.png
  frontend/src/assets/image/retrospectStep.png
  frontend/src/assets/image/studyingStep.png
  frontend/src/assets/images/heroImage.jpg
  frontend/src/assets/images/heroImage.webp
  frontend/src/assets/images/planningStep.jpg
  frontend/src/assets/images/planningStep.webp
  frontend/src/assets/images/retrospectStep.jpg
  frontend/src/assets/images/retrospectStep.webp
  frontend/src/assets/images/studyingStep.jpg
  frontend/src/assets/images/studyingStep.webp
  frontend/src/assets/sounds/alarm.mp3
  frontend/src/components/common/Image/Image.tsx
  frontend/src/components/landing/LandingMainSection/LandingMainSection.tsx
  frontend/src/components/landing/MenuTrigger/MenuTrigger.tsx
  frontend/src/components/landing/StartSection/StartSection.tsx
  frontend/src/components/landing/StudyStepGuide/StudyStepGuide.tsx
  frontend/src/components/progress/Timer/Timer.tsx
  frontend/src/components/record/MemberRecordContents/MemberRecordContents.tsx
  frontend/src/components/record/MemberRecordList/MemberRecordList.tsx
  frontend/src/components/record/StudyInformation/StudyInformation.tsx
  frontend/src/components/record/StudyInformation/StudyInformationSkeleton.tsx
  frontend/src/components/record/StudyInformation/style.ts
  frontend/src/fonts/Pretendard1.otf
  frontend/src/fonts/Pretendard2.otf
  frontend/src/fonts/Pretendard3.otf
  frontend/src/fonts/Pretendard4.otf
  frontend/src/fonts/Pretendard5.otf
  frontend/src/fonts/Pretendard6.otf
  frontend/src/fonts/Pretendard7.otf
  frontend/src/fonts/Pretendard8.otf
  frontend/src/fonts/Pretendard9.otf
  frontend/src/fonts/font.css
  frontend/src/router/index.tsx
  frontend/src/styles/globalStyle.ts
  frontend/src/types/index.d.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
  frontend/yarn.lock
Labels: FE, refactor, performance

#543 [FE] sourceFiles 경로 변경
  jenkins/frontend-develop.jenkinsfile
Labels: FE, refactor

#548 [FE] 모바일 환경에서의 구글 로그인 아이콘 위치 수정
  frontend/src/components/landing/BugReportingLink/BugReportingLink.tsx
  frontend/src/components/landing/ChattingLink/ChattingLink.tsx
  frontend/src/components/landing/LoginModalContents/LoginModalContents.tsx
Labels: FE, UI

#549 [FE] favicon 및 og 태그 설정
  frontend/public/favicon-blue.ico
  frontend/public/favicon-green.ico
  frontend/public/favicon-red.ico
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/og-image.png
  frontend/src/components/progress/StudyBoard/StudyBoard.tsx
  frontend/src/components/progress/Timer/Timer.tsx
  frontend/src/constants/asset.ts
  frontend/src/utils/dom.ts
Labels: FE, feature, UI

#551 [FE] 빌드 설정 변경 및 favicon, og image 경로 수정
  frontend/public/assets/favicon-blue.ico
  frontend/public/assets/favicon-green.ico
  frontend/public/assets/favicon-red.ico
  frontend/public/assets/favicon.ico
  frontend/public/assets/og-image.png
  frontend/public/index.html
  frontend/src/constants/asset.ts
  frontend/webpack.common.js
Labels: FE, refactor

#550 [BE] 참여 코드 저장 위치를 in memory에서 MySQL로 옮긴다
  backend/src/main/java/harustudy/backend/participantcode/domain/GenerationStrategy.java
  backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
  backend/src/main/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepository.java
  backend/src/main/java/harustudy/backend/participantcode/repository/ParticipantCodeRepository.java
  backend/src/main/java/harustudy/backend/study/service/PomodoroStudyService.java
  backend/src/test/java/harustudy/backend/participantcode/domain/ParticipantCodeTest.java
  backend/src/test/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepositoryTest.java
Labels: BE, feature

#553 [BE] 참여 코드 엔티티가 BaseEntity를 상속하도록 한다.
  backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
Labels: bug, BE, feature

#556 [FE] production jenkins 스크립트 변경
  jenkins/frontend-production.jenkinsfile
Labels: FE, devops

#560 [BE] ParticipantCode 관련 오류 수정
  backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
Labels: bug, BE

#561 [BE] ParticipantCode 관련 오류 수정
  backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
Labels: bug, BE

#569 [BE] 기존 api 중 폴링으로 인한 변경 반영, studyId로 참여코드 조회 api 구현
  backend/src/main/java/harustudy/backend/config/FilterConfig.java
  backend/src/main/java/harustudy/backend/participant/domain/Participant.java
  backend/src/main/java/harustudy/backend/participant/dto/ParticipantResponse.java
  backend/src/main/java/harustudy/backend/participantcode/controller/ParticipantCodeController.java
  backend/src/main/java/harustudy/backend/participantcode/dto/ParticipantCodeResponse.java
  backend/src/main/java/harustudy/backend/participantcode/repository/ParticipantCodeRepository.java
  backend/src/main/java/harustudy/backend/participantcode/service/ParticipantCodeService.java
  backend/src/main/java/harustudy/backend/study/controller/StudyController.java
  backend/src/main/java/harustudy/backend/study/dto/CreateStudyResponse.java
  backend/src/main/java/harustudy/backend/study/dto/StudyResponse.java
  backend/src/main/java/harustudy/backend/study/service/StudyService.java
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
  backend/src/test/java/harustudy/backend/participantcode/service/ParticipantCodeServiceTest.java
Labels: BE, feature

#575 [BE] 대기방 페이지 폴링 기능 구현하기
  backend/src/main/java/harustudy/backend/participant/domain/Participant.java
  backend/src/main/java/harustudy/backend/participant/repository/ParticipantRepository.java
  backend/src/main/java/harustudy/backend/participant/service/ParticipantService.java
  backend/src/main/java/harustudy/backend/study/domain/Study.java
  backend/src/main/java/harustudy/backend/view/controller/PollingController.java
  backend/src/main/java/harustudy/backend/view/dto/WaitingResponse.java
  backend/src/main/java/harustudy/backend/view/service/PollingService.java
  backend/src/test/java/harustudy/backend/content/repository/ContentRepositoryTest.java
  backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java
  backend/src/test/java/harustudy/backend/integration/ContentIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/MemberIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ParticipantIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/PollingIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
  backend/src/test/java/harustudy/backend/participant/domain/ParticipantTest.java
  backend/src/test/java/harustudy/backend/participant/service/ParticipantServiceTest.java
  backend/src/test/java/harustudy/backend/view/service/PollingServiceTest.java
Labels: BE, feature

#583 [FE] Button isLoading 일 때, 중복 클릭 방지
  frontend/src/components/common/Button/Button.tsx
Labels: bug, FE

#578 [BE] 이미 시작한 스터디 신규 참여 차단 로직 구현
  backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/participant/service/ParticipantService.java
  backend/src/main/java/harustudy/backend/study/exception/StudyAlreadyStartedException.java
  backend/src/test/java/harustudy/backend/participant/service/ParticipantServiceTest.java
Labels: BE, feature

#577 [BE] 진행 페이지 폴링 기능 구현하기
  backend/src/main/java/harustudy/backend/participant/service/ParticipantService.java
  backend/src/main/java/harustudy/backend/study/repository/StudyRepository.java
  backend/src/main/java/harustudy/backend/view/controller/PollingController.java
  backend/src/main/java/harustudy/backend/view/dto/ProgressResponse.java
  backend/src/main/java/harustudy/backend/view/service/PollingService.java
  backend/src/test/java/harustudy/backend/integration/ViewIntegrationTest.java
  backend/src/test/java/harustudy/backend/participant/service/ParticipantServiceTest.java
Labels: BE, feature

#579 [BE] 제출한 인원 조회하는 기능 구현하기
  backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/content/domain/Content.java
  backend/src/main/java/harustudy/backend/content/service/ContentService.java
  backend/src/main/java/harustudy/backend/polling/controller/PollingController.java
  backend/src/main/java/harustudy/backend/polling/dto/ProgressResponse.java
  backend/src/main/java/harustudy/backend/polling/dto/SubmitterResponse.java
  backend/src/main/java/harustudy/backend/polling/dto/SubmittersResponse.java
  backend/src/main/java/harustudy/backend/polling/dto/WaitingResponse.java
  backend/src/main/java/harustudy/backend/polling/exception/CannotSeeSubmittersException.java
  backend/src/main/java/harustudy/backend/polling/exception/CurrentCycleContentNotExistsException.java
  backend/src/main/java/harustudy/backend/polling/service/PollingService.java
  backend/src/main/java/harustudy/backend/polling/service/SubmitterCheckingStrategy.java
  backend/src/main/java/harustudy/backend/view/service/PollingService.java
  backend/src/test/java/harustudy/backend/integration/PollingIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ViewIntegrationTest.java
  backend/src/test/java/harustudy/backend/polling/service/PollingServiceTest.java
  backend/src/test/java/harustudy/backend/view/service/PollingServiceTest.java
Labels: BE, feature

#584 [BE] 폴링 기능 구현
  backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/config/FilterConfig.java
  backend/src/main/java/harustudy/backend/content/domain/Content.java
  backend/src/main/java/harustudy/backend/content/service/ContentService.java
  backend/src/main/java/harustudy/backend/participant/domain/Participant.java
  backend/src/main/java/harustudy/backend/participant/dto/ParticipantResponse.java
  backend/src/main/java/harustudy/backend/participant/repository/ParticipantRepository.java
  backend/src/main/java/harustudy/backend/participant/service/ParticipantService.java
  backend/src/main/java/harustudy/backend/participantcode/controller/ParticipantCodeController.java
  backend/src/main/java/harustudy/backend/participantcode/dto/ParticipantCodeResponse.java
  backend/src/main/java/harustudy/backend/participantcode/repository/ParticipantCodeRepository.java
  backend/src/main/java/harustudy/backend/participantcode/service/ParticipantCodeService.java
  backend/src/main/java/harustudy/backend/polling/controller/PollingController.java
  backend/src/main/java/harustudy/backend/polling/dto/ProgressResponse.java
  backend/src/main/java/harustudy/backend/polling/dto/SubmitterResponse.java
  backend/src/main/java/harustudy/backend/polling/dto/SubmittersResponse.java
  backend/src/main/java/harustudy/backend/polling/dto/WaitingResponse.java
  backend/src/main/java/harustudy/backend/polling/exception/CannotSeeSubmittersException.java
  backend/src/main/java/harustudy/backend/polling/exception/CurrentCycleContentNotExistsException.java
  backend/src/main/java/harustudy/backend/polling/service/PollingService.java
  backend/src/main/java/harustudy/backend/polling/service/SubmitterCheckingStrategy.java
  backend/src/main/java/harustudy/backend/study/controller/StudyController.java
  backend/src/main/java/harustudy/backend/study/domain/Study.java
  backend/src/main/java/harustudy/backend/study/dto/CreateStudyResponse.java
  backend/src/main/java/harustudy/backend/study/dto/StudyResponse.java
  backend/src/main/java/harustudy/backend/study/exception/StudyAlreadyStartedException.java
  backend/src/main/java/harustudy/backend/study/repository/StudyRepository.java
  backend/src/main/java/harustudy/backend/study/service/StudyService.java
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/content/repository/ContentRepositoryTest.java
  backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java
  backend/src/test/java/harustudy/backend/integration/ContentIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/MemberIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ParticipantIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/PollingIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ViewIntegrationTest.java
  backend/src/test/java/harustudy/backend/participant/domain/ParticipantTest.java
  backend/src/test/java/harustudy/backend/participant/service/ParticipantServiceTest.java
  backend/src/test/java/harustudy/backend/participantcode/service/ParticipantCodeServiceTest.java
  backend/src/test/java/harustudy/backend/polling/service/PollingServiceTest.java
Labels: BE, feature

#588 [BE] scale-out 용 젠킨스 스크립트 생성
  jenkins/backend-production2.jenkinsfile
Labels: BE, feature

#581 [FE] Tabs 컴포넌트 기능 추가
  frontend/__test__/StudyRecord.test.tsx
  frontend/src/assets/icons/ArrowIcon.tsx
  frontend/src/components/common/Tabs/TabList.tsx
  frontend/src/components/common/Tabs/TabListScrollButton.tsx
  frontend/src/components/common/Tabs/hooks/useTabListScroll.tsx
  frontend/src/components/record/ProgressRecord/ProgressRecord.tsx
  frontend/src/mocks/handlers/index.ts
Labels: FE, feature, UI

#593 [BE] participant에서 content 생성 로직 분리
  backend/src/main/java/harustudy/backend/participant/domain/Participant.java
  backend/src/main/java/harustudy/backend/participant/service/ParticipantService.java
  backend/src/test/java/harustudy/backend/content/repository/ContentRepositoryTest.java
  backend/src/test/java/harustudy/backend/content/service/ContentServiceTest.java
  backend/src/test/java/harustudy/backend/integration/ContentIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/MemberIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ParticipantIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/PollingIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ViewIntegrationTest.java
  backend/src/test/java/harustudy/backend/member/service/MemberServiceTest.java
  backend/src/test/java/harustudy/backend/participant/service/ParticipantServiceTest.java
  backend/src/test/java/harustudy/backend/participantcode/service/ParticipantCodeServiceTest.java
  backend/src/test/java/harustudy/backend/polling/service/PollingServiceTest.java
  backend/src/test/java/harustudy/backend/testutils/EntityManagerUtil.java
Labels: BE, refactor

#597 [FE] 스터디 방식 페이지 구현 및 스터디 시작 플로우 수정
  frontend/__test__/CreateStudyPage.test.tsx
  frontend/__test__/LandingPage.test.tsx
  frontend/src/assets/icons/ArrowIcon.tsx
  frontend/src/components/common/Select/SelectTrigger.tsx
  frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
  frontend/src/components/create/hooks/useCreateStudy.ts
  frontend/src/components/landing/LandingButton/LandingButton.tsx
  frontend/src/components/mode/StudyModeContent/StudyModeContent.tsx
  frontend/src/components/mode/StudyModeItem/StudyModeItem.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/api/useMutation.ts
  frontend/src/pages/CreateStudy.tsx
  frontend/src/pages/StudyMode.tsx
  frontend/src/router/index.tsx
  frontend/src/types/study.ts
Labels: FE, feature, refactor, UI

#601 [FE] 학습 선택 문구 변경
  frontend/src/components/mode/StudyModeContent/StudyModeContent.tsx
  frontend/src/pages/CreateStudy.tsx
Labels: FE, refactor, UI
