Repository woowacourse-teams/2023-haru-study, pull requests merged in 2023-08, with the labels that each got.

#226 [FE] 도메인 용어 및 문장 상수화
  frontend/src/components/board/GuideContents/GuideContents.tsx
  frontend/src/components/board/PlanningForm/PlanningForm.tsx
  frontend/src/components/board/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/board/StudyingForm/StudyingForm.tsx
  frontend/src/components/board/Timer/Timer.stories.tsx
  frontend/src/components/common/QuestionAnswer/QuestionAnswer.tsx
  frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
  frontend/src/components/record/AnswerQuestion/AnswerQuestion.tsx
  frontend/src/components/record/MemberRecord/MemberRecord.tsx
  frontend/src/constants/study.ts
  frontend/src/utils/getKeys.ts
Labels: FE, refactor

#227 [FE] Sidebar 문구 스터디 시간에 따라 유동적으로 바뀌도록 수정
  frontend/src/components/board/Sidebar/Sidebar.tsx
Labels: bug, FE

#228 [BE] 변경된 api/v2에 맞게 설계
  backend/src/main/java/harustudy/backend/common/EntityNotFoundException.java
  backend/src/main/java/harustudy/backend/content/controller/PomodoroContentController.java
  backend/src/main/java/harustudy/backend/content/controller/PomodoroContentControllerV2.java
  backend/src/main/java/harustudy/backend/content/dto/PomodoroContentResponse.java
  backend/src/main/java/harustudy/backend/content/dto/PomodoroContentResponses.java
  backend/src/main/java/harustudy/backend/content/dto/PomodoroContentsResponse.java
  backend/src/main/java/harustudy/backend/content/dto/WritePlanRequest.java
  backend/src/main/java/harustudy/backend/content/dto/WriteRetrospectRequest.java
  backend/src/main/java/harustudy/backend/content/service/PomodoroContentService.java
  backend/src/main/java/harustudy/backend/content/service/PomodoroContentServiceV2.java
  backend/src/main/java/harustudy/backend/member/controller/MemberController.java
  backend/src/main/java/harustudy/backend/member/controller/MemberControllerV2.java
  backend/src/main/java/harustudy/backend/member/dto/GuestRegisterRequest.java
  backend/src/main/java/harustudy/backend/member/dto/MemberResponseV2.java
  backend/src/main/java/harustudy/backend/member/dto/MembersResponseV2.java
  backend/src/main/java/harustudy/backend/member/service/MemberServiceV2.java
  backend/src/main/java/harustudy/backend/participantcode/controller/ParticipantCodeController.java
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressControllerV2.java
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroStatus.java
  backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressResponseV2.java
  backend/src/main/java/harustudy/backend/progress/repository/PomodoroProgressRepository.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressServiceV2.java
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomController.java
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV2.java
  backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomResponseV2.java
  backend/src/main/java/harustudy/backend/room/service/PomodoroRoomService.java
  backend/src/main/java/harustudy/backend/room/service/PomodoroRoomServiceV2.java
  backend/src/test/java/harustudy/backend/content/service/PomodoroContentServiceTest.java
  backend/src/test/java/harustudy/backend/integration/FindRoomIntegrationTest.java
  backend/src/test/java/harustudy/backend/progress/repository/PomodoroProgressRepositoryTest.java
Labels: BE, feature

#235 [BE] PomodoroRoom 관련 테스트 및 리팩터링
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomController.java
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV2.java
  backend/src/main/java/harustudy/backend/room/dto/MemberDto.java
  backend/src/main/java/harustudy/backend/room/dto/ParticipateRequest.java
  backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomAndMembersResponse.java
  backend/src/main/java/harustudy/backend/room/dto/ReParticipateRequest.java
  backend/src/main/java/harustudy/backend/room/service/PomodoroRoomService.java
  backend/src/main/java/harustudy/backend/room/service/PomodoroRoomServiceV2.java
  backend/src/test/java/harustudy/backend/integration/AuthenticateIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/CreateRoomIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/FindRoomIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/ParticipateRoomIntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/PomodoroRoomIntegrationTest.java
  backend/src/test/java/harustudy/backend/room/service/CreatePomodoroPomodoroRoomServiceTest.java
  backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceTest.java
  backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceV2Test.java
Labels: BE, refactor

#241 [FE] Select Height 수정 및 border 수정
  frontend/src/components/common/Select/Select.stories.tsx
  frontend/src/components/common/Select/SelectItem.tsx
  frontend/src/components/common/Select/SelectList.tsx
  frontend/src/components/common/Select/SelectTrigger.tsx
Labels: FE, refactor

#244 [FE] 예상 시간 텍스트 수정
  frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
Labels: FE, refactor

#236 [BE] PomodoroProgress 관련 테스트 및 리팩토링
  backend/src/main/java/harustudy/backend/content/service/PomodoroContentService.java
  backend/src/main/java/harustudy/backend/content/service/PomodoroContentServiceV2.java
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressResponse.java
  backend/src/main/java/harustudy/backend/progress/dto/RoomAndProgressStepResponse.java
  backend/src/main/java/harustudy/backend/progress/exception/IllegalProgressStateException.java
  backend/src/main/java/harustudy/backend/progress/exception/StudyPomodoroProgressException.java
  backend/src/main/java/harustudy/backend/progress/repository/PomodoroProgressRepository.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressServiceV2.java
  backend/src/test/java/harustudy/backend/content/service/PomodoroContentServiceTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/PomodoroProgressIntegrationTest.java
  backend/src/test/java/harustudy/backend/progress/domain/PomodoroProgressTest.java
  backend/src/test/java/harustudy/backend/progress/repository/PomodoroProgressRepositoryTest.java
  backend/src/test/java/harustudy/backend/progress/service/PomodoroProgressServiceTest.java
  backend/src/test/java/harustudy/backend/progress/service/PomodoroProgressServiceV2Test.java
Labels: BE, refactor

#243 [BE] Member 관련 테스트 및 리팩터링
  backend/src/main/java/harustudy/backend/member/controller/MemberController.java
  backend/src/main/java/harustudy/backend/member/controller/MemberControllerV2.java
  backend/src/main/java/harustudy/backend/member/domain/Member.java
  backend/src/main/java/harustudy/backend/member/service/MemberService.java
  backend/src/main/java/harustudy/backend/member/service/MemberServiceV2.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
  backend/src/test/java/harustudy/backend/integration/MemberIntegrationTest.java
  backend/src/test/java/harustudy/backend/member/domain/MemberTest.java
  backend/src/test/java/harustudy/backend/member/service/MemberServiceV2Test.java
Labels: BE, refactor

#248 [FE] 스터디 진행 페이지 웹 접근성
  frontend/src/api/index.ts
  frontend/src/components/board/Sidebar/Sidebar.tsx
  frontend/src/components/board/Timer/Timer.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx
  frontend/src/components/common/Typography/Typography.tsx
  frontend/src/hooks/board/useTimer.ts
  frontend/src/utils/http.ts
Labels: FE, feature

#247 [FE] 참여하기 페이지 접근시 로딩 스피너 추가
  frontend/src/api/index.ts
  frontend/src/pages/StudyPreparation.tsx
Labels: FE, refactor

#252 [FE] Input 컴포넌트 UI/UX 개선
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
  frontend/src/components/preparation/MemberRegister/MemberRegister.tsx
  frontend/src/components/preparation/ParticipationCodeCopier/ParticipationCodeCopier.tsx
  frontend/src/components/preparation/ParticipationCodeInput/ParticipationCodeInput.tsx
Labels: FE, refactor

#254 [FE] 브라우저 비활성탭일 때 타이머 시간 느리게 가는 버그 수정
  frontend/src/hooks/board/useStudyBoard.ts
  frontend/src/hooks/board/useTimer.ts
Labels: bug, FE

#259 [BE] memberId가 이미 있지만 다른 스터디를 참여할 때 null이 아닌 404내려주는 문제
  backend/src/main/java/harustudy/backend/member/service/MemberService.java
Labels: bug, BE, refactor

#260 [FE] 개설 요청, 참여 코드 인증 요청, 참여 요청 hook 분리
  frontend/src/api/index.ts
  frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
  frontend/src/components/participation/ParticipationCodeInput/ParticipationCodeInput.tsx
  frontend/src/components/preparation/MemberRegister/MemberRegister.tsx
  frontend/src/hooks/create/useCreateStudy.ts
  frontend/src/hooks/participation/useParticipationCode.ts
  frontend/src/hooks/preparation/useCheckIsMember.ts
  frontend/src/hooks/preparation/useRegisterMember.ts
  frontend/src/pages/StudyParticipation.tsx
  frontend/src/pages/StudyPreparation.tsx
Labels: FE, refactor

#291 [FE] 사용자 피드백 구현
  frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx
  frontend/src/components/landing/LandingContents/LandingContents.tsx
  frontend/src/components/participation/MemberRegister/MemberRegister.tsx
  frontend/src/components/participation/MemberRestart/MemberRestart.tsx
  frontend/src/components/participation/ParticipationCodeCopier/ParticipationCodeCopier.tsx
  frontend/src/hooks/participation/useCheckIsMember.ts
  frontend/src/hooks/participation/useRegisterMember.ts
  frontend/src/pages/CreateStudy.tsx
  frontend/src/pages/StudyParticipation.tsx
  frontend/src/pages/StudyPreparation.tsx
  frontend/src/pages/layout/StudyParticipationLayout.tsx
Labels: FE, feature

#265 [FE] 스터디 기록 페이지 API 훅 분리 및 v2 적용
  frontend/src/api/index.ts
  frontend/src/components/record/MemberRecord/MemberRecord.tsx
  frontend/src/components/record/MemberRecordList/MemberRecordList.tsx
  frontend/src/components/record/RecordContents/RecordContents.tsx
  frontend/src/hooks/record/useMemberRecord.ts
  frontend/src/hooks/record/useStudyRecord.ts
  frontend/src/mocks/handlers/studyRecordHandlers.ts
Labels: FE, refactor

#293 [BE] Prometheus gradle 설정
  backend/build.gradle
  backend/src/main/resources/application.yml
Labels: BE, feature

#294 [FE] 타이머 시간 음수로 표기되는 버그 수정
  frontend/src/hooks/board/useTimer.ts
Labels: bug, FE

#296 [FE] 프론트엔드 환경 설정
  frontend/src/components/board/Timer/Timer.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/QuestionAnswer/QuestionAnswer.tsx
  frontend/src/components/common/Tabs/TabList.tsx
  frontend/src/components/common/Typography/Typography.tsx
  frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
  frontend/src/components/landing/Hero/Hero.tsx
  frontend/src/components/landing/LandingContents/LandingContents.tsx
  frontend/src/components/participation/ParticipationCodeCopier/ParticipationCodeCopier.tsx
  frontend/src/fonts/Pretendard1.otf
  frontend/src/fonts/Pretendard2.otf
  frontend/src/fonts/Pretendard3.otf
  frontend/src/fonts/Pretendard4.otf
  frontend/src/fonts/Pretendard5.otf
  frontend/src/fonts/Pretendard6.otf
  frontend/src/fonts/Pretendard7.otf
  frontend/src/fonts/Pretendard8.otf
  frontend/src/fonts/Pretendard9.otf
  frontend/src/fonts/SCDream1.otf
  frontend/src/fonts/SCDream2.otf
  frontend/src/fonts/SCDream3.otf
  frontend/src/fonts/SCDream4.otf
  frontend/src/fonts/SCDream5.otf
  frontend/src/fonts/SCDream6.otf
  frontend/src/fonts/SCDream7.otf
  frontend/src/fonts/SCDream8.otf
  frontend/src/fonts/SCDream9.otf
  frontend/src/fonts/font.css
  frontend/src/styles/globalStyle.ts
  frontend/tsconfig.json
Labels: bug, FE, refactor

#297 [FE] 메뉴 컴포넌트 trigger 프롭스 기능 추가
  frontend/src/components/common/Menu/Menu.stories.tsx
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/common/Menu/MenuItem.tsx
  frontend/src/components/landing/LandingContents/LandingContents.tsx
Labels: FE, feature

#285 [BE] Logback 설정
  backend/src/main/java/harustudy/backend/common/CachingFilter.java
  backend/src/main/java/harustudy/backend/common/ExceptionAdvice.java
  backend/src/main/java/harustudy/backend/common/LoggingInterceptor.java
  backend/src/main/java/harustudy/backend/config/InterceptorConfig.java
  backend/src/main/resources/default-appender.xml
  backend/src/main/resources/error-appender.xml
  backend/src/main/resources/http-appender.xml
  backend/src/main/resources/logback-spring.xml
Labels: BE, feature

#299 [BE] logback 로그 actuator 관련 설정
  backend/src/main/resources/application.yml
  backend/src/main/resources/default-appender.xml
  backend/src/main/resources/error-appender.xml
  backend/src/main/resources/http-appender.xml
Labels: BE, feature

#302 [FE] OAuth 기능 구현
  frontend/.gitignore
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/index.ts
  frontend/src/constants/routes.ts
  frontend/src/contexts/MemberInfoProvider.tsx
  frontend/src/mocks/handlers/authHandler.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/Auth.tsx
  frontend/src/pages/Login.tsx
  frontend/src/router/index.tsx
  frontend/src/types/api.ts
  frontend/src/types/auth.ts
  frontend/src/types/member.ts
  frontend/src/utils/getUrlQuery.ts
  frontend/src/utils/http.ts
  frontend/src/utils/params.ts
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: FE, feature

#316 [BE] 운영 및 개발 서버 DB 분리
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-production.yml
  backend/src/main/resources/application.yml
Labels: BE, feature

#318 [BE] 개발서버 flyway 설정 변경 및 프로파일 문제 해결
  backend/src/main/resources/application-develop.yml
Labels: BE, refactor

#319 [FE] 웹팩 환경(prod, dev) 설정
  frontend/package.json
  frontend/src/pages/Login.tsx
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
  frontend/yarn.lock
Labels: FE, feature, setting

#325 [BE] 에러코드 정의
  backend/src/main/java/harustudy/backend/common/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/participantcode/exception/ParticipantCodeExpiredException.java
Labels: BE, feature

#324 [BE] SwaggerConfig 메서드 분리 및 순서 재정렬
  backend/src/main/java/harustudy/backend/config/swagger/SwaggerConfig.java
Labels: documentation, BE, refactor

#327 [BE] production, develop 서버 로그가 한 파일에 기록되는 문제
  backend/src/main/resources/default-appender.xml
  backend/src/main/resources/error-appender.xml
  backend/src/main/resources/http-appender.xml
  backend/src/main/resources/logback-spring.xml
Labels: BE, feature

#331 [FE] OAuth 리다랙트 경로 상대 경로로 적용
  frontend/src/pages/Login.tsx
Labels: bug, FE

#333 [BE] 백엔드 인가 관련 API Swagger 문서화
  backend/src/main/java/harustudy/backend/content/controller/PomodoroContentControllerV3.java
  backend/src/main/java/harustudy/backend/content/dto/WritePlanRequestV3.java
  backend/src/main/java/harustudy/backend/content/dto/WriteRetrospectRequestV3.java
  backend/src/main/java/harustudy/backend/member/controller/MemberControllerV3.java
  backend/src/main/java/harustudy/backend/member/dto/GuestRegisterRequest.java
  backend/src/main/java/harustudy/backend/member/dto/MemberResponseV3.java
  backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressRequestV3.java
  backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressResponseV3.java
  backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressesResponseV3.java
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV2.java
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV3.java
  backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomResponseV3.java
  backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomsResponseV3.java
Labels: documentation, BE, feature

#348 [BE] Contents 관련 인가 기능 추가
  backend/src/main/java/harustudy/backend/auth/dto/AuthMember.java
  backend/src/main/java/harustudy/backend/content/controller/PomodoroContentController.java
  backend/src/main/java/harustudy/backend/content/service/PomodoroContentService.java
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
Labels: BE, feature

#344 [BE] PomdoroProgress 관련 인가 기능 추가
  backend/src/main/java/harustudy/backend/auth/dto/AuthMember.java
  backend/src/main/java/harustudy/backend/content/controller/PomodoroContentController.java
  backend/src/main/java/harustudy/backend/content/service/PomodoroContentService.java
  backend/src/main/java/harustudy/backend/member/repository/MemberRepository.java
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/progress/dto/ParticipateStudyRequest.java
  backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressRequest.java
  backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressResponse.java
  backend/src/main/java/harustudy/backend/progress/dto/PomodoroProgressesResponse.java
  backend/src/main/java/harustudy/backend/progress/repository/PomodoroProgressRepository.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
  backend/src/main/java/harustudy/backend/room/repository/PomodoroRoomRepository.java
  backend/src/test/java/harustudy/backend/progress/domain/PomodoroProgressTest.java
  backend/src/test/java/harustudy/backend/progress/service/PomodoroProgressServiceTest.java
Labels: BE, feature

#345 [BE] PomodoroRoom 관련 인가 기능 추가 및 api 수정 사항 반영
  backend/src/main/java/harustudy/backend/common/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/progress/repository/PomodoroProgressRepository.java
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomController.java
  backend/src/main/java/harustudy/backend/room/dto/CreatePomodoroRoomResponse.java
  backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomResponse.java
  backend/src/main/java/harustudy/backend/room/dto/PomodoroRoomsResponse.java
  backend/src/main/java/harustudy/backend/room/repository/PomodoroRoomRepository.java
  backend/src/main/java/harustudy/backend/room/service/PomodoroRoomService.java
  backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceTest.java
Labels: BE, feature

#342 [BE] Member 관련 인가 기능 추가
  backend/src/main/java/harustudy/backend/common/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/member/controller/MemberController.java
  backend/src/main/java/harustudy/backend/member/domain/Member.java
  backend/src/main/java/harustudy/backend/member/dto/MemberResponse.java
  backend/src/main/java/harustudy/backend/member/exception/MemberHasInvalidAuthorizationException.java
  backend/src/main/java/harustudy/backend/member/service/MemberService.java
  backend/src/test/java/harustudy/backend/member/domain/MemberTest.java
  backend/src/test/java/harustudy/backend/member/service/MemberServiceTest.java
Labels: BE, feature

#358 [FE] API 통신 커스텀 에러
  frontend/.eslintrc
  frontend/jest.config.json
  frontend/src/errors/index.ts
  frontend/src/types/api.ts
  frontend/src/utils/http.ts
  frontend/tsconfig.paths.json
  frontend/webpack.common.js
Labels: FE, refactor

#359 [BE] Progress 관련 Exception 문서화
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
Labels: BE, feature

#360 [BE] Room 관련 Exception 문서화
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomController.java
Labels: documentation, BE

#361 [BE] ExceptionAdvice에 예외 핸들링 로직 구현
  backend/src/main/java/harustudy/backend/auth/AuthInterceptor.java
  backend/src/main/java/harustudy/backend/auth/infrastructure/GoogleOauthClient.java
  backend/src/main/java/harustudy/backend/auth/service/AuthService.java
  backend/src/main/java/harustudy/backend/common/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/content/controller/PomodoroContentController.java
  backend/src/main/java/harustudy/backend/content/service/PomodoroContentService.java
  backend/src/main/java/harustudy/backend/member/controller/MemberController.java
  backend/src/main/java/harustudy/backend/member/exception/MemberHasInvalidAuthorizationException.java
  backend/src/main/java/harustudy/backend/member/exception/MemberNotParticipatedException.java
  backend/src/main/java/harustudy/backend/member/service/MemberService.java
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
  backend/src/main/java/harustudy/backend/progress/exception/InvalidPomodoroProgressException.java
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomController.java
  backend/src/main/java/harustudy/backend/room/exception/DuplicatedNicknameException.java
  backend/src/test/java/harustudy/backend/common/ExceptionMapperTest.java
  backend/src/test/java/harustudy/backend/member/service/MemberServiceTest.java
Labels: documentation, BE, feature

#356 [BE] 스터디 참여 시 콘텐츠 생성 기능
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
  backend/src/main/java/harustudy/backend/auth/dto/TokenResponse.java
  backend/src/main/java/harustudy/backend/auth/exception/RefreshTokenCookieNotExistsException.java
  backend/src/main/java/harustudy/backend/auth/service/AuthService.java
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
Labels: BE, feature

#343 [FE] 스터디 기록 페이지 API 변경
  frontend/src/api/index.ts
  frontend/src/assets/icons/CalenderIcon.tsx
  frontend/src/components/record/MemberRecord/MemberRecord.tsx
  frontend/src/components/record/MemberRecordList/MemberRecordList.tsx
  frontend/src/components/record/RecordContents/RecordContents.tsx
  frontend/src/components/record/StudyInformation/StudyInformation.tsx
  frontend/src/contexts/MemberInfoProvider.tsx
  frontend/src/errors/index.ts
  frontend/src/hooks/record/useMemberRecord.ts
  frontend/src/hooks/record/useStudyRecord.ts
  frontend/src/mocks/handlers/authHandler.ts
  frontend/src/mocks/handlers/studyBoardHandler.ts
  frontend/src/mocks/handlers/studyRecordHandlers.ts
  frontend/src/types/api.ts
  frontend/src/types/study.ts
Labels: FE, feature, refactor

#365 [BE] Locaiton header 자원 URI 수정
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
Labels: BE, feature

#373 [BE] CORS 및 preflight 설정
  backend/src/main/java/harustudy/backend/auth/AuthInterceptor.java
  backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
Labels: BE, feature

#374 [BE] AllowOrigin이 제대로 인식되지 않던 문제 해결
  backend/src/main/java/harustudy/backend/config/WebMvcConfig.java
  backend/src/test/resources/application.yml
Labels: BE, refactor

#385 [BE] 멤버 프로필 조회 시 불필요한 memberId를 담지 않도록 수정
  backend/src/main/java/harustudy/backend/member/controller/MemberController.java
  backend/src/main/java/harustudy/backend/member/service/MemberService.java
  backend/src/test/java/harustudy/backend/member/service/MemberServiceTest.java
Labels: BE, feature

#379 [FE] Study Record Page 기능 개선
  frontend/src/assets/icons/ResetIcon.tsx
  frontend/src/components/common/Accordion/AccordionSkeleton.tsx
  frontend/src/components/record/MemberRecord/MemberRecord.tsx
  frontend/src/components/record/MemberRecordList/MemberRecordList.tsx
  frontend/src/components/record/RecordContents/RecordContents.tsx
  frontend/src/hooks/record/useStudyRecord.ts
Labels: FE, feature, UI

#386 [FE] memberId 필드명 수정
  frontend/src/hooks/participation/useCheckProgresses.ts
  frontend/src/hooks/participation/useRegisterProgress.ts
  frontend/src/mocks/handlers/authHandler.ts
  frontend/src/types/member.ts
Labels: bug, FE

#380 [FE] 닉네임 뒤 이/가 적용
  frontend/src/components/record/ProgressRecord/ProgressRecord.tsx
  frontend/src/mocks/handlers/studyRecordHandlers.ts
Labels: bug, FE, UI

#389 [BE] Member 영속화 시 필드 순서 조정 및 refresh token이 여러번 저장되는 문제 해결
  backend/src/main/java/harustudy/backend/auth/domain/RefreshToken.java
  backend/src/main/java/harustudy/backend/auth/repository/RefreshTokenRepository.java
  backend/src/main/java/harustudy/backend/auth/service/AuthService.java
Labels: BE, refactor

#357 [FE] Not Found Page 적용
  frontend/src/pages/NotFoundPage.tsx
  frontend/src/router/index.tsx
Labels: bug, FE, feature, UI

#392 [FE] 유저 정보 불러오기 리팩터링
  frontend/src/api/index.ts
  frontend/src/components/record/StudyRecordContents/StudyRecordContents.tsx
  frontend/src/contexts/MemberInfoProvider.tsx
  frontend/src/mocks/handlers/authHandler.ts
Labels: FE, refactor

#368 [FE] Header Profile Badge
  frontend/src/assets/icons/UserProfileIcon.tsx
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/landing/LandingContents/LandingContents.tsx
  frontend/src/components/landing/MemberProfile/MemberProfile.tsx
  frontend/src/components/landing/MenuTrigger/MenuTrigger.tsx
  frontend/src/contexts/MemberInfoProvider.tsx
  frontend/src/styles/common.ts
  frontend/src/types/member.ts
Labels: FE, feature, UI

#393 [FE] 스터디 진행 플로우 새로운 api 적용
  frontend/src/api/index.ts
  frontend/src/components/board/GuideContents/GuideContents.tsx
  frontend/src/components/board/PlanningForm/PlanningForm.tsx
  frontend/src/components/board/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/board/StudyingForm/StudyingForm.tsx
  frontend/src/hooks/board/usePlanningForm.ts
  frontend/src/hooks/board/useRetrospectForm.ts
  frontend/src/hooks/board/useStudyBoard.ts
  frontend/src/hooks/board/useStudyingForm.ts
  frontend/src/mocks/handlers/studyBoardHandler.ts
  frontend/src/pages/StudyBoard.tsx
  frontend/src/types/api.ts
  frontend/src/types/study.ts
Labels: FE, refactor

#396 [BE] 로그인 시 설정한 쿠키가 브라우저 창 종료 시 삭제되는 문제
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
Labels: BE, refactor

#397 [BE] refresh 요청 시에도 쿠키 path '/' 으로 설정
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
Labels: BE, refactor

#377 [BE] 멤버가 스터디에 참여하지 않았다면 타인의 진행도를 볼 수 없게 수정
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
  backend/src/test/java/harustudy/backend/progress/service/PomodoroProgressServiceTest.java
Labels: BE, refactor

#401 [BE] 스터디 참여할 때의 검증 로직 수정
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
Labels: BE, refactor

#394 [BE] 서버에서 발생하는 로그 시간이 현재 시간과 일치하지 않는 문제
  backend/src/main/resources/logback-spring.xml
Labels: BE, refactor

#405 [BE] 1.1.0 버전에 맞는 flyway schema 추가
  backend/src/main/resources/db/migration/V1.1__add-auth.sql
  backend/src/test/resources/application.yml
Labels: BE, feature

#415 [BE] 스터디에 학습 기록이 존재할 때 처음부터 진행하는 플로우에서 발생하는 문제
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
Labels: BE, feature

#411 [FE] 선택 질문 숨기기(토글) 기능 및 여러 디자인 수정
  frontend/src/assets/icons/ArrowIcon.tsx
  frontend/src/components/board/PlanningForm/PlanningForm.tsx
  frontend/src/components/board/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/board/StudyingForm/StudyingForm.tsx
  frontend/src/components/board/Timer/Timer.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/QuestionAnswer/QuestionAnswer.tsx
  frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx
  frontend/src/components/common/Typography/Typography.tsx
  frontend/src/components/landing/Hero/Hero.tsx
  frontend/src/hooks/board/useRetrospectForm.ts
  frontend/src/pages/Landing.tsx
Labels: FE, feature, UI

#417 [BE] progress delete api swagger 문서 추가 #416
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
Labels: documentation, BE

#418 [FE] 질문 가이드 기능 구현
  frontend/src/components/board/GuideModal/GuideModal.tsx
  frontend/src/components/board/PlanningForm/PlanningForm.tsx
  frontend/src/components/board/StepContents/StepContents.tsx
  frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx
  frontend/src/constants/study.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/StudyBoard.tsx
Labels: FE, feature, UI

#410 [FE] 로그아웃 기능 고도화 및 로그인시 로그인 페이지 접근 제한 기능 구현
  frontend/src/components/landing/MemberProfile/MemberProfile.tsx
  frontend/src/contexts/MemberInfoProvider.tsx
  frontend/src/utils/cookie.ts
Labels: FE, feature

#414 [FE] Alert Modal 버튼 디자인 변경
  frontend/src/components/common/Modal/Template/Alert.tsx
Labels: FE, feature, UI

#422 [FE] Input validation 추가
  frontend/src/hooks/common/useInput.ts
Labels: bug, FE, refactor

#424 [FE] ProgressId Delete 요청 추가
  frontend/src/api/index.ts
  frontend/src/hooks/participation/useCheckProgresses.ts
  frontend/src/types/api.ts
  frontend/src/utils/http.ts
Labels: FE, feature

#426 [ALL] 하루스터디 v1.1.1 배포 👏
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
  backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
  backend/src/main/java/harustudy/backend/progress/service/PomodoroProgressService.java
  frontend/src/api/index.ts
  frontend/src/assets/icons/ArrowIcon.tsx
  frontend/src/components/board/GuideModal/GuideModal.tsx
  frontend/src/components/board/PlanningForm/PlanningForm.tsx
  frontend/src/components/board/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/board/StepContents/StepContents.tsx
  frontend/src/components/board/StudyingForm/StudyingForm.tsx
  frontend/src/components/board/Timer/Timer.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Modal/Template/Alert.tsx
  frontend/src/components/common/QuestionAnswer/QuestionAnswer.tsx
  frontend/src/components/common/QuestionTextarea/QuestionTextarea.tsx
  frontend/src/components/common/Typography/Typography.tsx
  frontend/src/components/landing/Hero/Hero.tsx
  frontend/src/components/landing/MemberProfile/MemberProfile.tsx
  frontend/src/constants/study.ts
  frontend/src/contexts/MemberInfoProvider.tsx
  frontend/src/hooks/board/useRetrospectForm.ts
  frontend/src/hooks/common/useInput.ts
  frontend/src/hooks/participation/useCheckProgresses.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/Landing.tsx
  frontend/src/pages/StudyBoard.tsx
  frontend/src/types/api.ts
  frontend/src/utils/cookie.ts
  frontend/src/utils/http.ts
Labels: release

#434 [FE] 참여코드가 없을 때 모달로 띄우기, 구글로 로그인 버튼 구현
  frontend/src/assets/icons/GoogleIcon.tsx
  frontend/src/components/participation/ParticipationCodeInput/ParticipationCodeInput.tsx
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/Login.tsx
Labels: FE, feature, UI

#435 [FE] 참여코드가 없을 때 모달로 띄우기, 구글로 로그인 버튼 구현 리팩터링
  frontend/src/components/participation/ParticipationCodeInput/ParticipationCodeInput.tsx
  frontend/src/pages/Login.tsx
Labels: FE, refactor

#436 [BE] 로컬 환경 ddl-auto 설정 명시, placeholder 제거
  backend/src/main/resources/application.yml
Labels: BE, refactor

#439 [BE] 에러코드 명세 페이지 구현
  backend/build.gradle
  backend/src/main/java/harustudy/backend/auth/exception/AuthorizationException.java
  backend/src/main/java/harustudy/backend/auth/exception/InvalidAccessTokenException.java
  backend/src/main/java/harustudy/backend/auth/exception/InvalidAuthorizationHeaderException.java
  backend/src/main/java/harustudy/backend/auth/exception/InvalidProviderNameException.java
  backend/src/main/java/harustudy/backend/auth/exception/InvalidRefreshTokenException.java
  backend/src/main/java/harustudy/backend/auth/exception/RefreshTokenCookieNotExistsException.java
  backend/src/main/java/harustudy/backend/auth/exception/RefreshTokenExpiredException.java
  backend/src/main/java/harustudy/backend/common/SwaggerExceptionResponse.java
  backend/src/main/java/harustudy/backend/common/exception/ErrorCodeView.java
  backend/src/main/java/harustudy/backend/common/exception/ExceptionAdvice.java
  backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/common/exception/ExceptionResponse.java
  backend/src/main/java/harustudy/backend/common/exception/ExceptionSituation.java
  backend/src/main/java/harustudy/backend/common/exception/HaruStudyException.java
  backend/src/main/java/harustudy/backend/config/swagger/SwaggerConfig.java
  backend/src/main/java/harustudy/backend/content/controller/PomodoroContentController.java
  backend/src/main/java/harustudy/backend/content/exception/PomodoroContentNotFoundException.java
  backend/src/main/java/harustudy/backend/member/controller/MemberController.java
  backend/src/main/java/harustudy/backend/member/exception/MemberNotFoundException.java
  backend/src/main/java/harustudy/backend/progress/controller/PomodoroProgressController.java
  backend/src/main/java/harustudy/backend/progress/exception/NicknameLengthException.java
  backend/src/main/java/harustudy/backend/progress/exception/PomodoroProgressNotFoundException.java
  backend/src/main/java/harustudy/backend/progress/exception/PomodoroProgressStatusException.java
  backend/src/main/java/harustudy/backend/progress/exception/ProgressNotBelongToRoomException.java
  backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomController.java
  backend/src/main/java/harustudy/backend/room/exception/ParticipantCodeExpiredException.java
  backend/src/main/java/harustudy/backend/room/exception/ParticipantCodeNotFoundException.java
  backend/src/main/java/harustudy/backend/room/exception/PomodoroRoomNameLengthException.java
  backend/src/main/java/harustudy/backend/room/exception/PomodoroTimePerCycleException.java
  backend/src/main/java/harustudy/backend/room/exception/PomodoroTotalCycleException.java
  backend/src/main/java/harustudy/backend/room/exception/RoomNotFoundException.java
  backend/src/main/resources/static/error-code.css
  backend/src/main/resources/templates/error-code.html
Labels: BE, feature

#441 [BE] refreshToken 쿠키 수명 설정 시 입력 값 오류
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
Labels: BE, refactor

#442 [BE] 참여코드 만료 기능 구현
  backend/src/main/java/harustudy/backend/HaruStudyApplication.java
  backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java
  backend/src/main/java/harustudy/backend/participantcode/domain/CodeGenerationStrategy.java
  backend/src/main/java/harustudy/backend/participantcode/domain/GenerationStrategy.java
  backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
  backend/src/main/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepository.java
  backend/src/test/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepositoryTest.java
  backend/src/test/java/harustudy/backend/room/domain/CodeGenerationStrategyTest.java
  backend/src/test/java/harustudy/backend/room/domain/ParticipantCodeTest.java
Labels: BE, feature

#445 [BE] 인수테스트 시나리오 추가
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceTest.java
Labels: BE, feature

#446 [BE] Auth 관련 테스트를 추가한다
  backend/src/main/java/harustudy/backend/auth/AuthArgumentResolver.java
  backend/src/main/java/harustudy/backend/auth/AuthInterceptor.java
  backend/src/main/java/harustudy/backend/auth/util/BearerAuthorizationParser.java
  backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
  backend/src/test/java/harustudy/backend/auth/AuthArgumentResolverTest.java
  backend/src/test/java/harustudy/backend/auth/AuthInterceptorTest.java
  backend/src/test/java/harustudy/backend/auth/service/AuthServiceTest.java
  backend/src/test/java/harustudy/backend/auth/util/BearerAuthorizationParserTest.java
  backend/src/test/java/harustudy/backend/auth/util/JwtTokenProviderTest.java
  backend/src/test/java/harustudy/backend/auth/util/OauthUserInfoExtractorTest.java
  backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
Labels: BE, feature

#451 [BE] AuthController RequestMapping 방식 통일
  backend/src/main/java/harustudy/backend/auth/controller/AuthController.java
Labels: BE, refactor
